BirthdayResearch/defiscan.live

- .github/workflows/defichain-dependencies.yml
- .github/workflows/oss-governance-project-pr.yml
> improved @defichain/* update workflow

- README.md
- public/robots.txt
> updated README.md and added robots.txt

- .github/dependabot.yml
- .github/governance.yml
- .github/workflows/oss-governance-labeler.yml
- .github/workflows/sync-labels.yml
/kind chore
- updated .github/workflows
- updated governance workflow
> updated mono-repo deps, workflow & github health files

- .github/CODEOWNERS
- .github/governance.yml
- .github/labeler.yml
- .github/labels.yml
- README.md
- package-lock.json
- package.json
- src/layouts/Default.tsx
- src/store/block.ts
- src/store/index.ts
/kind chore
All state reducers in this store must be designed for global use and placed in `src/store` directory. Reducer that is not meant to be global must not be part of RootState.
Non-global states should be managed independently within their own React Component/Page.
> Added react-redux in src/store

- .babelrc
- .github/workflows/ci.yml
- .github/workflows/ci/wait-for
- .gitignore
- README.md
- cypress.json
- cypress/integration/layouts/header.ts
- cypress/plugins/index.ts
- cypress/support/commands.ts
- cypress/support/index.ts
- docker-compose.yml
- package-lock.json
- package.json
/kind chore
End-to-end test with CI-enabled local playground that will collect coverage at each PR.
Fixes https://github.com/DeFiCh/explorer/issues/29
> Added Cypress E2E with Coverage 

- .github/workflows/ci.yml
- cypress.json
- cypress/integration/layouts/header.ts
- src/layouts/contexts/PlaygroundContext.tsx
> on CI, cypress not to install and wait-on localhost:3000 to be ready

- .github/workflows/ci.yml
- README.md
> Updated codecov config

- .github/CODEOWNERS
- docker-compose.yml
> Bump defichain dependencies & docker-compose.yml

- .gitignore
/kind chore
We don't want to be committing test artifacts to the repo.
Fixes #79
> Added cypress/videos to gitignore.

- .gitignore
/kind chore
Not to commit testing artifacts to repo.
Fixes #85
> Added cypress/screenshots to gitignore

- src/layouts/contexts/api/Environment.ts
> disable testnet as it's not deployed in ocean yet

- .github/governance.yml
- .github/labels.yml
/kind chore
Commonly used on `DeFiCh/wallet`, added because it was missing in this repo.
> added ui-ux label governance

- src/layouts/contexts/api/NetworkQuery.tsx
- src/layouts/contexts/index.ts
- tsconfig.json
/kind chore
Added tsconfig.json config path mapping for cleaner code for common imports.
```ts
import { useNetworkContext } from '@contexts'
import { DeFiChainLogo } from '@components/icons/DeFiChainLogo;
```
> Added tsconfig.json config path mapping for cleaner code for common imports

- src/layouts/Default.tsx
/kind chore
Partial fix of #39
> Added basic site wide open graph and meta tags

- package-lock.json
- package.json
- src/layouts/components/Footer.tsx
- src/layouts/components/Header.tsx
/kind feature
- Added `@headlessui/react` for headless UI implementation, a package created by tailwind
- Added `react-icons` to fix #63
- Added `react-number-format` for number formatting
- Implemented NetworkMenu for network switching
- Updated `<Footer/>` links to link to existing websites
Fixes #44 
Fixes #63
> `<Header/>` & `<Footer/>`

- src/pages/404.tsx
> added 404 page

- src/layouts/contexts/api/Environment.ts
/kind feature
Enabled since it has been deployed in ocean.
> Enabled TestNet network

- .github/CODEOWNERS
> updated CODEOWNERS to include @aikchun @siradji

- src/pages/transactions/[txid].tsx
/kind feature
Added pages/transactions/[txid].tsx for temporary redirect to the old explorer.
> Added pages/transactions/[txid].tsx for temporary redirect to the old explorer

- src/layouts/components/Header.tsx
/kind feature
Implement header stats from the new `/stats` endpoint.
Fixes part of https://github.com/DeFiCh/scan/issues/91 although it's not implemented at the store level, it will work for now.
> updated header with stats from /stats endpoint

- docker-compose.yml
> Bump docker-compose.yml

- package-lock.json
- package.json
- src/layouts/components/Header.tsx
- src/styles/globals.css
- tailwind.config.js
/kind fix
> https://fonts.google.com/specimen/IBM+Plex+Sans#standard-styles
Added font-family and updated UI to match design.
- also added `date-fns` please use that for date formatting
> added font-family and updated UI to match design

- package-lock.json
- package.json
- src/pages/_app.tsx
/kind feature
To show client-side loading.
> added nextjs-progressbar

- package-lock.json
- package.json
- src/components/commons/Breadcrumb.tsx
- src/components/prices/PriceFeed.tsx
- src/components/prices/PriceOracleTable.tsx
- src/components/prices/PriceTickerDetail.tsx
- src/pages/index.tsx
- src/pages/prices/[symbol].tsx
- src/pages/prices/index.tsx
- tailwind.config.js
/kind feature
Added initial `/prices/[symbol].tsx` page
- ~~Prices copy information is missing, need to fill them up. #122~~
- ~~Not responsive optimized yet~~
- Will add graph in another PR
> Added `/prices/[symbol].tsx` page

- .github/workflows/ci.yml
/kind chore
So that cypress tests don't build in between tests.
> `ci.yml` to build before running npm run build

- package-lock.json
- package.json
- src/components/prices/PriceGraph.tsx
- src/components/prices/PriceOracleTable.tsx
- src/layouts/components/Header.tsx
- src/layouts/contexts/WhaleContext.tsx
- src/pages/prices/[symbol].tsx
> Add historical price graph for each ticker for at least 24 hours

- src/layouts/components/Footer.tsx
/kind feature
Social media links on footer
Fixes #94
> Added social Links  in  footer

- src/cms/oracles/index.ts
- src/pages/prices/index.tsx
/kind feature
Add urls to provider feeds
Fixes #
> Add urls to provider feeds

- _redirects
- netlify.toml
> Added HSTS and updated _redirects to include http://

- src/layouts/Default.tsx
- src/layouts/components/Footer.tsx
- src/styles/globals.css
/kind fix
- Disabled body scrolling
- Added no scaling meta tag
- Fixed overflow for `<Footer/>`
> fixed responsive sizing issues

- src/components/prices/PriceGraph.tsx
> fixed too much data causes chart not to rendered properly

- docker-compose.yml
> Bump whale:0.8.6 in docker-compose.yml

- cypress/integration/layouts/header.spec.ts
- cypress/support/index.ts
> default cypress to always test on MainNet

- src/layouts/components/Header.tsx
> fix hide HeaderMenu on mobile before route starts

- .eslintrc
- .husky/pre-commit
- next.config.js
- package-lock.json
- package.json
> added lint-staged

- src/components/commons/Head.tsx
- src/layouts/components/Header.tsx
- src/pages/dex/index.tsx
> removed suffix USD to prefix $

- .github/CODEOWNERS
- .idea/dictionaries/fuxing.xml
- src/components/commons/popover/HoverPopover.tsx
- src/layouts/components/Header.tsx
- src/pages/dex/index.tsx
/kind chore
On defiscan.live, only block rewards are included in the APR calculation. With commission, the expected APR is much higher. We will update this soon.
Also fixed `<Header/>` clickable area.
> Added APR HoverPopover

- cypress/integration/layouts/header.spec.ts
- cypress/integration/routing/network_query.spec.ts
- netlify.toml
- src/pages/index.tsx
> `/` to redirect to `/prices` instead

- docker-compose.yml
/kind fix
This will prevent certain 503 errors on the playground when testing.
> added -rpcworkqueue=512 to docker-compose.yml

- docker-compose.yml
> Bump `playground:0.8.6` & `whale:0.8.9` in docker-compose.yml

- .eslintrc
> updated eslint to ignore cypress dir

- cypress/integration/pages/prices-[symbol].spec.ts
- cypress/integration/pages/prices.spec.ts
- src/components/commons/Breadcrumb.tsx
- src/components/prices/PriceFeed.tsx
- src/components/prices/PriceOracleTable.tsx
- src/components/prices/PriceTickerDetail.tsx
/kind chore
Added E2E tests for `/prices`. 
This PR also updated the icon used in PriceFeed.
> added e2e tests for `/prices`

- .github/workflows/ci-e2e.yml
- .github/workflows/ci.yml
> added github workflow concurrency to cancel-in-progress

- cypress/integration/pages/tokens/tokens.spec.ts
- src/components/commons/AdaptiveTable.tsx
- src/components/commons/CursorPagination.tsx
- src/layouts/components/Footer.tsx
- src/layouts/components/Header.tsx
- src/pages/tokens/index.tsx
/kind feature
Tokens page implementation #45 
Fixes #
> `/tokens` page

- package-lock.json
- package.json
- src/components/commons/AdaptiveTable.tsx
> add classNames utility

- src/components/commons/OverflowTable.tsx
- src/components/commons/UnitSuffix.tsx
/kind feature
Cherry-picked from `/blocks` page so we can start using them now.
> Cherry-picked UnitSuffix.tsx and OverflowTable.tsx from `/blocks`

- src/pages/tokens/index.tsx
> rename "Default Defi token" to "DeFiChain" in `/tokens`

- cypress/integration/pages/prices/prices-[symbol].spec.ts
- cypress/integration/pages/prices/prices.spec.ts
> refactor `/prices` to fix flaky tests

- cypress/integration/pages/blocks/index.spec.ts
- cypress/integration/pages/prices/prices.spec.ts
- cypress/integration/pages/tokens/tokens.spec.ts
- cypress/integration/routing/network_query.spec.ts
- cypress/support/commands.ts
> added interceptServerSideWait to fix flaky page load test

- cypress/integration/pages/tokens/tokens.spec.ts
/kind feature
Added E2E test for mobile device
Fixes #194
>  E2E test for mobile /tokens

- src/pages/blocks/index.tsx
> Fix blocks page table using an input for size

- .github/PULL_REQUEST_TEMPLATE.md
/kind docs
Adds developer checklist to ensure tasks are completed before submitting PR for review
Fixes #
> developer checklist

- .github/PULL_REQUEST_TEMPLATE.md
/kind chore
Moved developer checklist down so that important descriptions appear above. (This section)
This makes PR previews on messaging channels much more readable and concise.
> moved developer checklist down so that important description appear above

- src/pages/dex/index.tsx
> fixed B/A wrong display on /dex

- .idea/dictionaries/fuxing.xml
- src/components/icons/assets/BTC.tsx
- src/components/icons/assets/DFI.tsx
- src/components/icons/assets/_Default.tsx
- src/components/icons/assets/dBCH.tsx
- src/components/icons/assets/dBTC.tsx
- src/components/icons/assets/dDFI.tsx
- src/components/icons/assets/dDOGE.tsx
- src/components/icons/assets/dETH.tsx
- src/components/icons/assets/dLTC.tsx
- src/components/icons/assets/dUSDC.tsx
- src/components/icons/assets/dUSDT.tsx
/kind refactor
- added viewBox to all icons
- converted _Default icon to use `<svg>` instead of `<div>`
> icons refactor and fixes

- src/layouts/components/Footer.tsx
/kind chore
Netlify requirement for backlinks. Netlify provided a badge for use.
I am using the light icon instead.
Fixes #255
> Added Netlify Open Source Icon

- src/components/commons/Container.tsx
- src/layouts/components/Footer.tsx
- src/layouts/components/Header.tsx
- src/pages/404.tsx
- src/pages/_app.tsx
- src/pages/blocks/index.tsx
- src/pages/dex/index.tsx
- src/pages/masternodes/index.tsx
- src/pages/prices/[symbol].tsx
- src/pages/prices/index.tsx
- src/pages/tokens/[id].tsx
- src/pages/tokens/index.tsx
- src/pages/transactions/[txid].tsx
/kind refactor
Added container implementation that is part of the design language.
https://www.figma.com/file/XdKJSI9TGYAf1VXJCQf2cZ/DeFiChain-Design-System?node-id=8%3A38093
> added Container.tsx that has been recently added to DeFi Scan DSM

- src/components/commons/AdaptiveList.tsx
- src/components/commons/CopyButton.tsx
- src/pages/blocks/[blockId]/index.tsx
- src/pages/blocks/index.tsx
/kind refactor
- clean up `CopyButton.tsx` to follow DSM and simplified the code
- updated blocks page to use `AdaptiveList.tsx` entirely. That component was created for the block detail page that is part of the common components.
- added testId to AdaptiveList.tsx
- refactored the code to use more components for better separation of concerns
- implemented all the remaining fields that are available and hid Block Reward due to API changes required.
@aikchun after you review this and merge it into your working branch, please update your test cases due to the breaking changes.
> refactor block details

- next-sitemap.js
- public/robots.txt
> fixed next-sitemap.js generate to disallow other networks

- src/components/dex/PoolPairs.tsx
/kind fix
Fix pool par price ratio, was displaying the wrong value due to precision issues.
> fixed pool pair price ratio display

- src/pages/_app.tsx
/kind fix
Removed spinner from NProgressbar to fix issue on mobile
Fixes #280
> Removed spinner from Nprogressbar

- .github/CODEOWNERS
> Updated CODEOWNERS to include @joeldavidw

- .idea/dictionaries/fuxing.xml
- src/pages/blocks/[blockId]/index.tsx
- src/pages/transactions/[txid].tsx
/kind refactor
Minor refactor to fix consistency with what was designed.
> refactor transaction page

- src/components/prices/PriceOracleTable.tsx
> Fixed margin and text alignment in cells

- cypress/integration/pages/prices/prices-[symbol].spec.ts
- src/components/prices/PriceOracleTable.tsx
/kind feature
Implemented Overflow table to make oraclesFeed more responsive
Fixes #261
> Converted OracleFeed to use Overflow table. 

- src/components/commons/CopyButton.tsx
- src/pages/blocks/[blockId]/index.tsx
/kind fix
Responsiveness issue on block/:id page
Fixes #310
> Fixed responsiveness issue on block/:id page

- src/layouts/components/Header.tsx
/kind fix
Show active nav link on header
Fixes #306
> Show active nav link on header

- src/layouts/components/Footer.tsx
/kind fix
Part of UI fixes and  pixel perfect design across projects. Footer on desktop does not match the designs. 
Fixes part of  #260
> Fixed footer

- docker-compose.yml
- package-lock.json
- package.json
- src/layouts/contexts/WhaleContext.tsx
> Bump @defichain/playground dependencies

- src/components/transactions/[txid]/TransactionDetails.tsx
- src/components/transactions/[txid]/TransactionHeadings.tsx
- src/components/transactions/[txid]/TransactionSummaryTable.tsx
- src/pages/transactions/[txid].tsx
/kind refactor
Refactored components in transaction page due to linting max number of code lines.
> refactored components in transaction page

- cypress/integration/pages/tokens/tokens.spec.ts
- src/components/address/[address]/AddressTokenTable.tsx
- src/pages/tokens/[id].tsx
- src/pages/tokens/index.tsx
/kind refactor
- Updated `/tokens` to use displaySymbol
- Updated `/address/*` to use the correct icon
Fixes #
Link: 
<details>
</details>
<details>
</details>
> updated token icon in /tokens & /address to match wallet display

- src/components/index/BlocksList.tsx
- src/components/index/TransactionsList.tsx
/kind
To make homepage more interactive
Fixes #506 
Link: 
<details>
</details>
<details>
</details>
> Make blocks and transactions list change color on hover on homepage

- babel.config.js
- package-lock.json
- package.json
/kind chore
Removes all data-testid attributes from production build.
> Strip data-testid from prod build

- src/pages/prices/index.tsx
/kind feature
Adds pagination to /prices
> Added pagination to `/prices`

- src/components/index/BlocksList.tsx
- src/components/index/TransactionsList.tsx
/kind fix
removed underline from blocks and txn
> Removed underline for homepage

- src/components/commons/OverflowTable.tsx
/kind feature
Update OverflowTable to follow the new design
> Updated OverflowTable hover state and added alignRight

- cypress/integration/pages/prices/prices-[symbol].spec.ts
- src/components/commons/popover/HoverPopover.tsx
- src/components/commons/popover/InfoHoverPopover.tsx
- src/components/prices/PriceTickerDetail.tsx
- src/components/transactions/[txid]/TransactionSummaryTable.tsx
/kind feature refactor
Updated alert symbols to info on `/price/:id`
Refactored all Info symbol popover into a component
Fixes #519
> Added InfoHoverPopover

- src/components/index/IndexHeader.tsx
- src/layouts/components/HeaderSearchBar.tsx
- src/pages/search/[query].tsx
/kind fix
Adds network context to old searchbar
**Note**
Quick fix before the new search bar is redesigned and pushed into production.
> Updated searchbar with network context

- _redirects
/kind chore
Added `explorer.defichain.io` domain in to _redirects to handle deprecation of `explorer.defichain.io` in the future.
> Added explorer.defichain.io into `_redirects`

- cypress/integration/pages/transactions/DfTx/ICXClaimDFCHTLC.spec.ts
- cypress/integration/pages/transactions/DfTx/ICXCloseOffer.spec.ts
- cypress/integration/pages/transactions/DfTx/ICXCloseOrder.spec.ts
- cypress/integration/pages/transactions/DfTx/ICXMakeOffer.spec.ts
- cypress/integration/pages/transactions/DfTx/ICXSubmitDFCHTLC.spec.ts
- cypress/integration/pages/transactions/DfTx/ICXSubmitEXTHTLC.spec.ts
- cypress/integration/pages/transactions/DfTx/TokenUpdateAny.spec.ts
- src/components/address/[address]/AddressTransactionTableRow.tsx
- src/components/commons/OverflowTable.tsx
- src/components/commons/TxIdLink.tsx
- src/components/prices/PriceOracleTable.tsx
- src/components/transactions/[txid]/DfTx/DfTxICXClaimDFCHTLC.tsx
- src/components/transactions/[txid]/DfTx/DfTxICXCloseOffer.tsx
- src/components/transactions/[txid]/DfTx/DfTxICXCloseOrder.tsx
- src/components/transactions/[txid]/DfTx/DfTxICXMakeOffer.tsx
- src/components/transactions/[txid]/DfTx/DfTxICXSubmitDFCHTLC.tsx
- src/components/transactions/[txid]/DfTx/DfTxICXSubmitEXTHTLC.tsx
- src/components/transactions/[txid]/DfTx/DfTxTokenUpdateAny.tsx
- src/pages/tokens/[id].tsx
/kind refactor
Fixes #495 
Link: 
<details>
</details>
<details>
</details>
> Make transaction links clickable

- src/components/commons/popover/HoverPopover.tsx
- src/layouts/components/Header.tsx
- src/layouts/components/HeaderCountBar.tsx
- src/layouts/components/HeaderNetworkMenu.tsx
- src/layouts/contexts/WhaleContext.tsx
/kind feature
Updates HeaderCountBar and mobile menu to new design
Fixes #505
> Updated HeaderCountBar and mobile menu

- src/pages/_app.tsx
/kind fix
Updates the colour of the progressbar to make it more visible against the new headerbar color
> Update progressbar color to be more visible

- package-lock.json
- package.json
- src/layouts/contexts/WhaleContext.tsx
/kind chore
Change testnet to use v0.13 and updated jellyfish deps
> Changed testnet to 'v0.13' and updated jellyfish deps

- _redirects
/kind chore
added .io redirects
> added .io redirects

- _redirects
> fixed redirect

- src/components/commons/popover/HoverPopover.tsx
- src/layouts/components/Footer.tsx
- src/store/stats.tsx
/kind feature
Adds network status to the footer
- Protocol
- Version
- Subversion
Fixes #
> Add network status to the footer

- src/layouts/contexts/WhaleContext.tsx
/kind chore
Updates mainnet to v0.13
> Updated mainnet to v0.13

- src/layouts/components/Footer.tsx
/kind fix
Adds a space between visit and defichain link in the footer
> `Footer` Minor UI Fix

- src/components/address/[address]/AddressTokenTable.tsx
/kind feature
Fixes #559 
Link: 
<details>
</details>
<details>
</details>
> Made Tokens clickable on address page

- src/layouts/components/Footer.tsx
/kind refactor
Updated versioning in footer to match external comms
> `Footer` Versioning update

- cypress/integration/pages/address/[address].spec.ts
> fixed address test

- cypress/integration/pages/tokens/tokens-[symbol].spec.ts
- cypress/integration/pages/vaults/[vaultid].spec.ts
- src/components/vaults/VaultMobileCard.tsx
- src/components/vaults/[vaultid]/LoanTotalInterestRate.tsx
- src/components/vaults/[vaultid]/VaultIdCollateralDetails.tsx
- src/components/vaults/[vaultid]/VaultIdDetails.tsx
- src/components/vaults/[vaultid]/VaultIdLoansDetails.tsx
- src/components/vaults/common/VaultCollateralizationRatio.tsx
- src/components/vaults/common/VaultDetailsListItem.tsx
- src/components/vaults/common/VaultNumberValues.tsx
- src/pages/vaults/[vaultid].tsx
- src/pages/vaults/index.tsx
/kind feature
Adds active prices to vaults
> Add active prices to `vaults`

- src/pages/_app.tsx
/kind fix
Updated progress bar color and size
> Updated progress bar color and size

- .github/dependabot.yml
- .github/workflows/defichain-dependencies.yml
> updated dependabot to ignore defichain dependency

- cypress/integration/pages/vaults/index.spec.ts
- src/components/vaults/VaultMobileCard.tsx
- src/components/vaults/[vaultid]/VaultIdDetails.tsx
- src/components/vaults/[vaultid]/VaultIdHeading.tsx
- src/pages/vaults/index.tsx
/kind feature
- Adds min collateralisation ratio to `/vaults`
- Adds thousand separator support for min collateralisation ratio 
- Removed warning banners for vault pages
> Add min collateralisation value to `vaults`

- src/components/oracles/OracleTickerDetail.tsx
/kind fix
Fixes #
Link: 
<details>
</details>
<details>
</details>
> Added Alt prop to price picker icon

- cypress/integration/pages/vaults/[vaultid].spec.ts
- src/components/vaults/[vaultid]/VaultIdDetails.tsx
- src/components/vaults/[vaultid]/VaultIdLoansDetails.tsx
> Updated vault page

- src/layouts/components/Header.tsx
/kind fix feature
- Fixes header getting overlapped issue
- Only shows shadow when page is scrolled (Mobile)
Fixes #595
> Fixed header issue and show shadow only when scrolled

- src/components/commons/PoolPairSymbol.tsx
> PoolPairSymbol first icon to have a higher z-index

- src/components/address/[address]/AddressSummaryTable.tsx
- src/components/address/[address]/AddressTokenTable.tsx
- src/components/address/[address]/AddressTransactionTableRow.tsx
- src/components/address/[address]/AddressVinVout.tsx
- src/components/commons/TokenSymbol.tsx
- src/components/commons/transactions/TransactionVectorRow.tsx
- src/components/index/IndexHeader.tsx
- src/components/oracles/OracleFeed.tsx
- src/components/oracles/OracleTickerDetail.tsx
- src/components/transactions/[txid]/DfTx/DfTxTokenCreate.tsx
- src/components/transactions/[txid]/DfTx/DfTxTokenUpdateAny.tsx
- src/components/transactions/[txid]/TransactionVinVout.tsx
- src/components/vaults/VaultMobileCard.tsx
- src/components/vaults/[vaultid]/VaultIdAuctionsDetails.tsx
- src/components/vaults/[vaultid]/VaultIdCollateralDetails.tsx
- src/components/vaults/[vaultid]/VaultIdDetails.tsx
- src/components/vaults/[vaultid]/VaultIdLoansDetails.tsx
- src/components/vaults/common/VaultDetailsListItem.tsx
- src/components/vaults/common/VaultTokenSymbols.tsx
- src/layouts/components/HeaderCountBar.tsx
- src/pages/oracles/index.tsx
- src/pages/vaults/index.tsx
/kind fix
Fixed margin issue on Safari <= 14.0
Issue lies with `gap` in flex boxes which is not supposed by Safari <= 14.0
> Updated all gaps in flex to space

- cypress/integration/pages/transactions/DfTx/SetCollateralToken.spec.ts
- src/components/transactions/[txid]/DfTx/DfTxSetCollateralToken.tsx
- src/components/transactions/[txid]/TransactionDfTx.tsx
/kind feature
Added `DfTxSetCollateralToken` to transaction page
Fixes part of #542
Link: 
<details>
</details>
<details>
</details>
> `DfTxSetCollateralToken`

- cypress/integration/pages/transactions/DfTx/SetDefaultLoanScheme.spec.ts
- src/components/transactions/[txid]/DfTx/DfTxSetDefaultLoanScheme.tsx
- src/components/transactions/[txid]/TransactionDfTx.tsx
/kind
Added `DfTxSetDefaultLoanScheme`
Fixes part of  #542 
Link: 
<details>
</details>
<details>
</details>
> `DfTxSetDefaultLoanScheme`

- cypress/integration/pages/transactions/DfTx/SetLoanToken.spec.ts
- src/components/transactions/[txid]/DfTx/DfTxSetLoanToken.tsx
- src/components/transactions/[txid]/TransactionDfTx.tsx
/kind feature
Fixes part of #542 
Link: 
<details>
</details>
<details>
</details>
> `DfTxSetLoanToken`

- cypress/integration/pages/transactions/DfTx/CreateVault.spec.ts
- src/components/transactions/[txid]/DfTx/DfTxCreateVault.tsx
- src/components/transactions/[txid]/TransactionDfTx.tsx
/kind feature
Fixes part of  #542 
Link: 
<details>
</details>
<details>
</details>
> `DfTxCreateVault`

- cypress/integration/pages/transactions/DfTx/UpdateVault.spec.ts
- src/components/transactions/[txid]/DfTx/DfTxUpdateVault.tsx
- src/components/transactions/[txid]/TransactionDfTx.tsx
/kind feature
Fixes part of #542 
Link: 
<details>
</details>
<details>
</details>
> `DfTxUpdatevault`

- cypress/integration/pages/dex/dex.spec.ts
- cypress/integration/pages/index.spec.ts
- cypress/integration/pages/masternodes/masternodes.spec.ts
- cypress/integration/pages/vaults/index.spec.ts
- src/components/commons/stats/StatItem.tsx
- src/components/commons/stats/StatsBar.tsx
- src/components/index/IndexHeader.tsx
- src/components/vaults/VaultStatsBar.tsx
- src/layouts/components/HeaderCountBar.tsx
- src/layouts/contexts/WhaleContext.tsx
- src/pages/dex/index.tsx
- src/pages/masternodes/index.tsx
- src/pages/vaults/index.tsx
- src/store/stats.tsx
- src/styles/globals.css
- tsconfig.json
/kind feature fix
- Added Stats bar for Vaults
- Update Stats Bar for Index
- Add loans to TVL in global stats bar
Fixes #460
https://deploy-preview-617--defi-scan.netlify.app/vaults
https://deploy-preview-617--defi-scan.netlify.app/
> Updates Stat Bars

- src/components/commons/popover/HoverPopover.tsx
- src/components/vaults/VaultMobileCard.tsx
- src/components/vaults/common/VaultDetailsListItem.tsx
/kind fix
Fixed HoverPopover components for mobile touches
> Implement touchstart/end instead on mobile for `HoverPopover`

- cypress/integration/pages/vaults/[vaultid].spec.ts
- src/layouts/contexts/WhaleContext.tsx
/kind chore
- Updates testnet to v0.16
> Update testnet to v0.16

- cypress/integration/pages/vaults/[vaultid].spec.ts
- src/components/vaults/VaultMobileCard.tsx
- src/components/vaults/[vaultid]/VaultIdAuctionsDetails.tsx
- src/components/vaults/[vaultid]/VaultIdDetails.tsx
- src/components/vaults/[vaultid]/VaultIdLoansDetails.tsx
- src/components/vaults/common/VaultCollateralizationRatio.tsx
- src/components/vaults/common/VaultStatus.tsx
- src/pages/vaults/[vaultid].tsx
- src/pages/vaults/index.tsx
- src/utils/vaults/LiquidatedVaultDerivedValues.tsx
/kind feature
- Increase `/vaults` pagination to 30
- Client side calculation for liquidated vaults (Total Loan/Collateral amounts & Collaterialisation Ratio)
> `Vaults` Update to include derived liquidated vault values

- content/prices/index.ts
- cypress/integration/pages/oracles/oracles.spec.ts
- src/components/oracles/OracleFeed.tsx
- src/pages/oracles/index.tsx
/kind fix
- Dynamic determination of Loan/Collateral Tokens
> Updated Oracles determination of Loan/Collateral Tokens

- src/components/commons/SearchBar.tsx
/kind fix
- Fixes icon not appearing
- Updated search helper message to include vaults
> Fix search bar icon and update help text

- cypress/integration/pages/tokens/tokens-[symbol].spec.ts
- src/components/commons/link/AddressLink.tsx
- src/components/commons/popover/WarningHoverPopover.tsx
- src/pages/tokens/[id].tsx
/kind feature
Fixes #
Link: 
<details>
</details>
<details>
</details>
> Added backing address to tokens `USDC USDT BTC BCH ETH DOGE LTC`

- src/layouts/contexts/WhaleContext.tsx
/kind chore
Update mainnet to v0.16
> bump mainnet to v0.16

- src/components/vaults/VaultStatsBar.tsx
- src/layouts/components/HeaderCountBar.tsx
/kind feature fix
- Added Collateralization Ratio to vaults stats
- Updated TVL popup values
> Added Collateralization Ratio to vaults stats and updated TVL

- cypress/integration/components/SearchBar.spec.ts
- src/components/commons/SearchBar.tsx
/kind fix
Fixed SearchBar keyboard navigation
> Fixed `SearchBar` keyboard navigation

- package-lock.json
- package.json
/kind fix
Revert cypress 9.1.0 to 9.0.0
> Revert cypress 9.1.0 to 9.0.0

- package-lock.json
- package.json
> Changed cypress versioning

- src/pages/oracles/index.tsx
/kind fix
Fixed oracle sort buttons layout
> Fixed oracle sort buttons layout

- cypress/integration/pages/vaults/[vaultid].spec.ts
- src/components/vaults/[vaultid]/VaultIdAuctionsDetails.tsx
- src/components/vaults/[vaultid]/VaultIdLoansDetails.tsx
/kind feature
Added usd prices to In liquidation auction details
Fixes #
Link: 
<details>
</details>
> `vaults` Added usd prices to In liquidation auction details

- src/components/commons/PoolPairSymbol.tsx
- src/components/dex/PoolPairs.tsx
/kind fix
- Updated PoolPair to use display symbol
> Fixed PoolPairSymbol

- cypress/integration/pages/address/[address].spec.ts
- cypress/integration/pages/transactions/DfTx/CompositeSwap.spec.ts
- src/components/transactions/[txid]/DfTx/DftxCompositeSwap.tsx
- src/components/transactions/[txid]/TransactionDfTx.tsx
/kind feature
Adds Composite Swap DfTx
Fixes Part of #542
> Add `DfTxCompositeSwap`

- src/components/commons/AdaptiveList.tsx
- src/components/commons/TokenSymbol.tsx
/kind fix
- Standardise token symbol placement
> Update tokensymbol placement

- cypress/integration/pages/transactions/DfTx/CompositeSwap.spec.ts
- src/components/transactions/[txid]/DfTx/DfTxCompositeSwap.tsx
- src/components/transactions/[txid]/TransactionDfTx.tsx
/kind fix
- Added margins to composite swap path
> Update Path margins

- cypress/integration/pages/transactions/DfTx/CloseVault.spec.ts
- cypress/integration/pages/transactions/DfTx/DepositToVault.spec.ts
- src/components/commons/link/VaultLink.tsx
- src/components/transactions/[txid]/DfTx/DfTxCloseVault.tsx
- src/components/transactions/[txid]/DfTx/DfTxDepositToVault.tsx
- src/components/transactions/[txid]/TransactionDfTx.tsx
/kind feature
Adds CloseVault and DepositToVault DfTx
Fixes Part of #542
> Adds `DfTxCloseVault`, `DfTxDepositToVault`

- src/pages/index.tsx
/kind chore
Limit number of LPs shown on homepage to 8
> Limit LPs on homepage to 8

- cypress/integration/pages/vaults/[vaultid].spec.ts
/kind fix
Fixed vaultid tests to dynamically locate a healthy vault
> Fixed vaultid tests

- src/components/address/[address]/AddressTransactionTable.tsx
/kind fix
Fixed infinite loop on address with no txns
> Fixed infinite loop on address with no txns

- src/components/vaults/VaultMobileCard.tsx
/kind fix
Fixes bug where vault links in mobile card are not clickable
Fixes #663
> Fixed mobile vault link

- src/pages/address/[address].tsx
- src/pages/tokens/[id].tsx
- src/pages/tokens/index.tsx
- src/pages/transactions/[txid].tsx
- src/pages/vaults/[vaultid].tsx
- src/pages/vaults/index.tsx
> add SEO tags for pages

- cypress/integration/pages/address/[address].spec.ts
- cypress/integration/pages/vaults/[vaultid].spec.ts
- src/components/address/[address]/AddressTokenTable.tsx
- src/components/address/[address]/AddressTransactionTable.tsx
/kind fix
- Added pagination to balance table
- Fixed pool pairs token symbols and name
> Fixed balances table on `Address` page

- src/components/index/LiquidityPoolList.tsx
/kind feature
Fixes #
Link: 
<details>
</details>
<details>
</details>
> Homepage Redesign: Liquidity section

- cypress/integration/pages/transactions/DfTx/AccountToAccount.spec.ts
- cypress/integration/pages/transactions/DfTx/PoolRemoveLiquidity.spec.ts
- src/components/transactions/[txid]/DfTx/DfTxAccountToAccount.tsx
/kind fix
Fixed dftx tests due to change to displaySymbols
> Fixed tests and layout

- cypress/integration/pages/address/[address].spec.ts
/kind fix
Updated address page test due to change in wallet balance
> Updated test due to change in wallet balances

- src/components/commons/TokenSymbol.tsx
- src/components/transactions/[txid]/DfTx/DfTxCompositeSwap.tsx
/kind fix feature
- Fixed token symbol placement
- Added functionality to change symbol placement of left or right
> Fixed TokenSymbol Component token symbol placement

- src/components/dex/PoolPairs.tsx
> APR on front-end

- src/components/dex/PoolPairs.tsx
- src/components/index/LiquidityPoolList.tsx
/kind fix
Added APR calculation on the frontend as outdated cache on the API server were still being served.
> Added APR calculation on the frontend

- src/components/dex/PoolPairs.tsx
- src/components/index/LiquidityPoolList.tsx
/kind chore
- Removal of APR calculation on the FE.
> Removed APR hotfix

- src/layouts/contexts/WhaleContext.tsx
> bump testnet to use v0.17

- cypress/integration/pages/transactions/DfTx/PayBackLoan.spec.ts
- src/components/transactions/[txid]/DfTx/DfTxPayBackLoan.tsx
- src/components/transactions/[txid]/TransactionDfTx.tsx
/kind feature
Fixes #
Link: 
<details>
</details>
<details>
</details>
> `DfTxPayBackLoan`

- src/layouts/contexts/WhaleContext.tsx
> Update mainnet to v0.17

- cypress/integration/pages/transactions/DfTx/PlaceAuctionBid.spec.ts
- src/components/transactions/[txid]/DfTx/DfTxPlaceAuctionBid.tsx
- src/components/transactions/[txid]/TransactionDfTx.tsx
/kind feature
Added PlaceAuctionBid DfTx with test
Fixes Part of #542
Link: https://deploy-preview-708--defi-scan.netlify.app/transactions/bddbd785df3e27c817c0e1054ebb04c1e932efd08a0e3f8f97663ddba6cf3d00
> Added PlaceAuctionBid DfTx with test

- src/pages/_app.tsx
/kind chore
Removal of notice banner
> Remove notice banner

- package-lock.json
- package.json
> Update to tailwindcss 3.0.0

- next-env.d.ts
- src/pages/index.tsx
/kind feature
Fixes #694 
Link: 
<details>
</details>
<details>
</details>
> Homepage props autorefresh

- src/styles/globals.css
- tailwind.config.js
/kind chore
Update of tailwind.config.js as required for the migration from tailwindcss v2 to v3
> Migration from tailwindcss v2 to v3

- cypress/integration/pages/transactions/DfTx/WithdrawFromVault.ts
- src/components/transactions/[txid]/DfTx/DfTxWithdrawFromVault.tsx
- src/components/transactions/[txid]/TransactionDfTx.tsx
/kind feature
Added DfTx Withdraw From Vault with tests
Fixes part of #542 
Link: https://deploy-preview-724--defi-scan.netlify.app/transactions/60f348e30726ea1aa7dcfab1b8442ca605be732674a76f5718b3adebd45f3ef1
> Added `WithdrawFromVault` DfTx with tests

- package.json
- src/styles/globals.css
- tailwind.config.js
/kind dependencies fix
Downgraded tailwind from v3 to v2. Due to drift between local and netlify/production builds
> Revert tailwind to v2

- .idea/dictionaries/joeldavid.xml
- src/components/vaults/common/VaultHealthBar.tsx
/kind fix
Fixed misspelled "collateralization" in healthbar
> Fixed misspelled collateralization and added to intellij dictionary

- cypress/integration/pages/vaults/index.spec.ts
- src/components/commons/stats/StatItem.tsx
- src/components/vaults/VaultStatsBar.tsx
/kind fix
Fixes #668
Link: 
<details>
</details>
<details>
</details>
> Updated Vaults Stasbar label

- cypress/integration/layouts/footer.spec.ts
- netlify.toml
- src/layouts/components/Footer.tsx
/kind fix
- Added Discord link
- Fixed LinkedIn, GitHub, YouTube casing
- Changed GitHub to point to DeFiCh org instead of ain
- Added test cases
Fixes #734
> `Footer` Added discord link and updated ui

- src/layouts/contexts/WhaleContext.tsx
> Bump WhaleApiClient to use v0.18

- src/pages/address/_components/AddressTokenTable.tsx
> list all token balance for address

- cypress/integration/pages/address/[address].spec.ts
- src/components/commons/sections/CollapsibleSection.tsx
- src/components/commons/sections/EmptySection.tsx
- src/pages/address/[address].page.tsx
- src/pages/address/_components/AddressBalances.tsx
- src/pages/address/_components/AddressTokenTable.tsx
- src/pages/address/_components/AddressTransactionTable.tsx
/kind feature
- Added collapsible sections to Address page
- Updated Address Balances UI
Link: https://deploy-preview-764--defi-scan.netlify.app/address/df1qpqe9dsaz9vu66vnzs4xvnqpv4mevf2u3kcx50n
> Updated `address` Balances UI

- netlify.toml
- package-lock.json
- package.json
Added @netlify/plugin-nextjs to netlify.toml and package.json
> Added @netlify/plugin-nextjs to netlify.toml and package.json

- next.config.js
- public/_headers
/kind fix
- Fixes image (data:) not loading due to CSP rules
> Fix image (data:) not loading due to CSP rules

- cypress/integration/pages/address/[address].spec.ts
- src/pages/address/[address].page.tsx
- src/pages/address/_components/AddressBalances.tsx
- src/pages/address/_components/AddressHeadings.tsx
- src/pages/address/_components/AddressTransactionTable.tsx
- src/pages/address/_components/AddressVaults.tsx
- src/pages/address/_components/ShowMoreButton.tsx
- src/pages/vaults/[vaultid]/_components/VaultIdDetails.tsx
- src/pages/vaults/_components/VaultMobileCard.tsx
- src/pages/vaults/_components/commons/VaultCollateralizationRatio.tsx
- src/pages/vaults/_components/commons/VaultNumberValues.tsx
- src/pages/vaults/_components/commons/VaultTable.tsx
- src/pages/vaults/_components/commons/VaultTableRow.tsx
- src/pages/vaults/_components/commons/VaultTokenSymbols.tsx
- src/pages/vaults/index.page.tsx
- src/pages/vaults/utils/LiquidatedVaultDerivedValues.tsx
/kind feature refactor
- Added vaults section to address page
- Refactored Vaults components into components
Fixes #522
Link: 
<details>
</details>
<details>
</details>
> Implemented `vaults` section in `address` page

- src/pages/vaults/_components/commons/VaultTokenSymbols.tsx
Signed-off-by: Suraj Auwal <siradjiawoual@gmail.com>
/kind fix
Fixes #733
Link: 
<details>
</details>
<details>
</details>
> Removed duplicate icons on vaults page

- src/pages/vaults/_components/commons/VaultTokenSymbols.tsx
/kind fix
Added undefined check to VaultTokenSymbols.
> Added undefined check

- next.config.js
- public/_headers
/kind fix
Added prefetch-src CSP rule
> Added prefetch-src

- src/components/icons/assets/signal/SignalCellular1.tsx
- src/components/icons/assets/signal/SignalCellular2.tsx
/kind fix
- Fixed Signal 1 & 2 svg
> Fixed Signal 1 & 2 svg

- cypress/integration/pages/address/[address].spec.ts
- cypress/integration/pages/index.spec.ts
- cypress/integration/pages/vaults/[vaultid].spec.ts
- src/components/commons/PoolPairSymbol.tsx
- src/components/commons/sections/CollapsibleSection.tsx
- src/components/index/BlocksList.tsx
- src/components/index/LiquidityPoolList.tsx
- src/components/index/TransactionsList.tsx
- src/pages/index.page.tsx
/kind feature fix
- Update Txn and Block Lists/Cards to match updated design
- Added tests for Txn, Blocks, LP sections
Fixes #692
> `homepage` redesign

- cypress/integration/pages/auctions/index.spec.ts
- cypress/integration/pages/vaults/[vaultid]/auctions/[index].spec.ts
- cypress/integration/pages/vaults/[vaultid]/index-InLiquidation.spec.ts
- cypress/integration/pages/vaults/[vaultid]/index.spec.ts
- src/pages/auctions/_components/commons/AuctionTimeLeft.tsx
- src/pages/auctions/_components/commons/BidAmountValue.tsx
- src/pages/vaults/[vaultid]/_components/VaultIdAuctionsDetails.tsx
- src/pages/vaults/[vaultid]/_components/VaultIdDetails.tsx
- src/pages/vaults/[vaultid]/auctions/[index].page.tsx
- src/pages/vaults/[vaultid]/auctions/_components/AuctionDetails.tsx
- src/pages/vaults/[vaultid]/auctions/_components/DesktopAuctionDetails.tsx
- src/pages/vaults/[vaultid]/auctions/_components/MobileAuctionDetails.tsx
- src/pages/vaults/_components/commons/VaultAuctionDetails.tsx
- src/pages/vaults/_components/commons/VaultDetailsListItem.tsx
- src/pages/vaults/_components/commons/VaultHealthBar.tsx
- src/pages/vaults/_components/commons/VaultNumberValues.tsx
- src/pages/vaults/_components/commons/VaultTokenSymbols.tsx
/kind feature
- Adds e2e tests for:
- Auctions
- Auction Details
- Vaults - In Liquidation
- Tests include checks to verify if there is any active auction running. If there isnt any the tests will be skipped
> Added `vaults` & `auctions` test

- src/layouts/Default.tsx
> Added announcement banner

- src/layouts/Default.tsx
> Remove announcement banner

- .github/governance.yml
- .github/labeler.yml
- .github/labels.yml
/kind chore
Added OCG and Auctions areas
> Updated governance - OCG & Auctions

- src/layouts/components/HeaderCountBar.tsx
/kind fix
Fix Header count items alignment
Fixes #808 
Link: 
<details>
</details>
<details>
</details>
> Align header count items on mobile

- src/components/icons/assets/tokens/_Default.tsx
- src/pages/vaults/_components/commons/RemainingTokensIcon.tsx
- src/pages/vaults/_components/commons/VaultTokenSymbols.tsx
/kind fix
- Updated Remaing tokens Icon
- Reduced shown icons to 3
Fixes #801
Link: 
<details>
</details>
<details>
</details>
> Vaults Icon redesign 

- src/pages/vaults/_components/commons/VaultHealthBar.tsx
/kind fix
Removed the margin between the colors to provide a more accurate representation
Fixes #836
> Removed margin to provide an accurate representation

- package-lock.json
- package.json
- Updates node-forge and nanoid
> Updated node-forge and nanoid deps

- src/components/icons/assets/tokens/_TokenDefault.tsx
- src/styles/globals.css
/kind fix
- Changed tokens font to IBM Plex Sans Condensed
- Updated font size
Fixes #
Link: 
<details>
</details>
<details>
</details>
> Token symbols font update

- cypress/integration/components/SearchBar.spec.ts
- cypress/integration/pages/address/[address].spec.ts
- src/components/commons/AdaptiveList.tsx
- src/pages/address/_components/AddressSummaryTable.tsx
/kind feature refactor
- Update `Balance` title in Address Summary Section to clarify that it is **UTXO Balance** only
Fixes #
Link: 
<details>
</details>
<details>
</details>
> `Address` Updated Balance title to UTXO Balance

- content/events/index.ts
/kind feature
- Updated events by slug to be case insensitive
- Added FCH to events
Link: https://deploy-preview-873--defi-scan.netlify.app/blocks/countdown/fortcanninghill
Link: https://deploy-preview-873--defi-scan.netlify.app/blocks/countdown/1605000
> Added FCH to `events`

- content/events/index.ts
- src/pages/blocks/countdown/[query]/_components/BlocksInfoSection.tsx
- src/pages/blocks/countdown/[query]/_components/CountdownSection.tsx
- src/pages/blocks/countdown/[query]/_components/InfoSection.tsx
/kind chore
- Added Jan dToken Reward Distribution
- Updated Block countdown Ui
> Updated blocks `countdown` UI and added new event

- src/pages/transactions/_components/DfTx/DfTxUnmapped.tsx
/kind fix
- Added Wrap to unmapped dftx
> Added wrap to unmapped dftx

- cypress/integration/pages/blocks/countdown/[height].spec.ts
- cypress/integration/pages/transactions/DfTx/SetGovernanceHeight.spec.ts
- src/pages/transactions/_components/DfTx/DfTxSetGovernanceHeight.tsx
- src/pages/transactions/_components/TransactionDfTx.tsx
/kind feature
- Implements SetGovernanceHeight DfTx
> Added `DfTx` - SetGovernanceHeight

- src/pages/oracles/index.page.tsx
/kind feature
- Sorts oracle alphabetically in each type (Crypto, Stocks etc.)
> Sort `oracles` alphabetically in each type

- src/layouts/contexts/WhaleContext.tsx
/kind chore
- Updated TestNet to v0.20
> Updated testnet to v0.20

- docker-compose.yml
- next-env.d.ts
/kind chore
PR to update `docker-compose.yml` to use the latest version and configuration.
> chore(docker-compose): update fork height on docker-compose

- src/layouts/contexts/WhaleContext.tsx
/kind chore
- Downgrade testnet to v0.19
> Downgrade testnet to v0.19

- src/layouts/contexts/WhaleContext.tsx
/kind chore
- Upgrade mainnet to v0.19
> Upgrade mainnet to v0.19

- src/components/commons/banner/WarningBanner.tsx
- src/layouts/Default.tsx
> Added announcement

- src/layouts/Default.tsx
> Remove banner

- cypress/integration/pages/vaults/index.spec.ts
- src/pages/vaults/_components/VaultStatsBar.tsx
/kind refactor
- Changed `Collateralized Vaults` to `Vaults` as the value reported has been corrected.
Fixes #911
- [ x Tested responsiveness (e.g, iPhone, iPad, Desktop)
> Updated VaultStatsBar

- src/components/commons/Breadcrumb.tsx
- src/components/commons/link/BlockLink.tsx
- src/components/commons/link/TxIdLink.tsx
- src/components/commons/link/VaultLink.tsx
- src/components/dex/PoolPairs.tsx
- src/layouts/components/Footer.tsx
- src/pages/address/_components/AddressBalances.tsx
- src/pages/address/_components/AddressTransactionTableRow.tsx
- src/pages/blocks/[blockId]/index.page.tsx
- src/pages/transactions/_components/DfTx/DfTxSetCollateralToken.tsx
- src/pages/transactions/_components/DfTx/DfTxUpdateVault.tsx
- src/pages/transactions/_components/TransactionSummaryTable.tsx
- src/pages/vaults/_components/VaultMobileCard.tsx
/kind refactor
Standardise all hyperlinks color to text-blue-500 from text-primary-500
Fixes #832
> Updated links colour

- src/layouts/contexts/WhaleContext.tsx
> testnet bump to 0.23

- src/layouts/contexts/WhaleContext.tsx
/kind chore
bumped mainnet to v0.23
> Bumped mainnet to v0.23

- src/pages/stats/burn.page.tsx
> Burn stats update to burn %

- src/layouts/contexts/WhaleContext.tsx
> Route mainnet and testnet to v0

- src/layouts/Default.tsx
- src/pages/auctions/_components/commons/BidAmountValue.tsx
- src/pages/vaults/[vaultid]/auctions/_components/DesktopAuctionDetails.tsx
- src/pages/vaults/[vaultid]/auctions/_components/MobileAuctionDetails.tsx
- src/pages/vaults/_components/commons/VaultAuctionDetails.tsx
- src/pages/vaults/hooks/CalculateAuctionsValue.tsx
- src/pages/vaults/hooks/TokenPrice.ts
- src/pages/vaults/utils/path-finding.tsx
- src/store/index.ts
- src/store/poolpairs.tsx
/kind fix
Updated following values in Auctions to use DEX price instead of Oracle price:
- Collateral token values
- min next bid value
Fixes #919
Link: 
<details>
</details>
<details>
</details>
> `Auction` - Update USD prices to use DEX price

- src/components/dex/PoolPairs.tsx
- src/layouts/contexts/WhaleContext.tsx
add commission to APR calculation
/kind feature
- Add 24H, 30D volume for PoolPair in `/dex`
- APR in `/dex` now includes commission
> add 24h, 30d volume for /dex

- src/components/dex/PoolPairs.tsx
/kind feature
Updated APR to show commission and rewards
> `DEX` Updated APR to show commission and rewards

- src/components/index/SupplyStats.tsx
> `Homepage` Fixed TVL units

- src/components/commons/banner/WarningBanner.tsx
- src/layouts/Default.tsx
> Added Testnet notification

- cypress/integration/pages/dex/dex.spec.ts
- src/components/commons/popover/HoverPopover.tsx
- src/components/commons/popover/MoreHoverPopover.tsx
- src/components/dex/PoolPairs.tsx
- src/pages/dex/index.page.tsx
/kind feature 
Fixes #987 & #986
Link:
> `DEX` Table Columns & APR Breakdown UI update

- cypress/integration/pages/auctions/index.spec.ts
- cypress/integration/pages/blocks/index.spec.ts
- cypress/integration/pages/dex/dex.spec.ts
- cypress/integration/pages/masternodes/masternodes.spec.ts
- cypress/integration/pages/tokens/tokens.spec.ts
- src/components/commons/CardList.tsx
- src/components/commons/link/AddressLink.tsx
- src/pages/blocks/_components/BlocksCards.tsx
- src/pages/blocks/_components/BlocksTable.tsx
- src/pages/blocks/index.page.tsx
- src/pages/dex/_components/APRInfo.tsx
- src/pages/dex/_components/PoolPairsCards.tsx
- src/pages/dex/_components/PoolPairsTable.tsx
- src/pages/dex/index.page.tsx
- src/pages/masternodes/_components/MasternodeCards.tsx
- src/pages/masternodes/_components/MasternodeTable.tsx
- src/pages/masternodes/index.page.tsx
- src/pages/tokens/_components/TokenCards.tsx
- src/pages/tokens/_components/TokenTable.tsx
- src/pages/tokens/index.page.tsx
- src/pages/vaults/_components/VaultMobileCard.tsx
/kind refactor
- Refactored Masternodes and Tokens page to use CardList component for better mobile support
Fixes #
Link:
> Refactored `Tokens` & `Masternodes`

- src/pages/dex/index.page.tsx
> fix(dex): list 100 poolpair at most instead of 30

- content/events/index.ts
/kind chore
Added mar dtoken rewards to countdown events
> Added dtoken mar rewards event

- cypress/integration/pages/blocks/index.spec.ts
- cypress/integration/pages/dex/[poolpairId].spec.ts
- package-lock.json
- package.json
- src/components/commons/CardList.tsx
- src/components/commons/UnitSuffix.tsx
- src/pages/blocks/_components/BlocksCards.tsx
- src/pages/dex/[poolpairId]/_components/PoolPairDetails.tsx
- src/pages/dex/[poolpairId]/_components/PoolPairGraph.tsx
- src/pages/dex/[poolpairId]/_components/SwapCards.tsx
- src/pages/dex/[poolpairId]/_components/SwapTable.tsx
- src/pages/dex/[poolpairId]/index.page.tsx
- src/pages/dex/_components/PoolPairsCards.tsx
- src/pages/dex/_components/PoolPairsTable.tsx
- src/pages/tokens/_components/TokenCards.tsx
- src/pages/tokens/_components/TokenTable.tsx
- src/pages/vaults/_components/VaultMobileCard.tsx
- src/pages/vaults/_components/commons/VaultAuctionDetails.tsx
/kind feature
Fixes #
Link: 
<details>
</details>
<details>
</details>
> `DEX` Poolpair page

- package-lock.json
- package.json
- src/layouts/contexts/WhaleContext.tsx
- src/pages/stats/burn.page.tsx
/kind chore
Bumped to ocean v0.27
> Updated packages and bumped to 0.27

- cypress/integration/pages/dex/[poolpairId].spec.ts
- src/pages/dex/[poolpairId]/index.page.tsx
/kind chore
Removes Volume graph from Individual Pool Pair page as it gives a false indication.
> `DEX`: Remove Volume graph

- cypress/integration/pages/dex/dex.spec.ts
- package-lock.json
- src/components/commons/CardList.tsx
- src/components/commons/OverflowTable.tsx
- src/pages/dex/_components/PoolPairsCards.tsx
- src/pages/dex/_components/PoolPairsTable.tsx
/kind feature
It adds the feature to allow sorting of the DEX by Total Liquidity, Volume (24H) or APR
Fixes #
<details>
</details>
<details>
</details>
> Added feature to sort for total liquidity, volume and apr on DEX page

- cypress/integration/pages/index.spec.ts
- src/components/commons/sections/CollapsibleSection.tsx
- src/components/index/IndexHeader.tsx
- src/components/index/StatCard.tsx
- src/components/index/SupplyStats.tsx
- src/pages/index.page.tsx
- src/store/stats.tsx
- src/utils/index/CalculatePercentage.ts
/kind chore fix
- Fixed Language
- Code Cleanup
- Server Render Stats value on first load.
Fixes #
> `Homepage` Fixed language in Stats

- src/pages/auctions/_components/commons/BidAmountValue.tsx
- src/pages/vaults/[vaultid]/auctions/_components/AuctionBiddingHistory.tsx
- src/pages/vaults/[vaultid]/auctions/_components/BiddingHistoryMobileCard.tsx
- src/pages/vaults/[vaultid]/auctions/_components/DesktopAuctionDetails.tsx
- src/pages/vaults/[vaultid]/auctions/_components/MobileAuctionDetails.tsx
- src/pages/vaults/_components/commons/VaultAuctionDetails.tsx
/kind fix feature
- Added bid counts to auctions and vault page. To allow users to easily identify auctions that are being actively bidded on
- Fixed bid number
Fixes #892
> Added bid number to vaults, auctions page and fixed bid numbers

- src/pages/tokens/[id].page.tsx
/kind fix
- Fixed category in /tokens/id page
Fixes #1048
Link: 
<details>
</details>
<details>
</details>
> `Tokens` Fixed token category

- src/layouts/contexts/WhaleContext.tsx
> Bumped whale to 0.31

- src/pages/vaults/[vaultid]/_components/VaultIdCollateralDetails.tsx
/kind fix feature
- Added DUSD collateral composition percentage
- Added DUSD collateral 99% collateral percentage 
https://deploy-preview-1052--defi-scan.netlify.app/vaults/fa520b61cffedc4293c2bf685d7b695b284cee2f248b64c1b60953bb774a4900
https://deploy-preview-1052--defi-scan.netlify.app/vaults/2b0940bb840f1c1276c7f5b3e19979ba4efddcf8dfd69dcd907f5c97462ea300
> Added DUSD composition percentage

- cypress/integration/pages/oracles/oracles-[symbol].spec.ts
- src/pages/oracles/_components/OracleGraph.tsx
/kind feature
Fixes #1040
Link: 
<details>
</details>
<details>
</details>
> Added graph period button for 1D, 7D & 30D

- src/pages/oracles/_components/OracleGraph.tsx
/kind fix
- Removed `??=` syntax and set default time explicitly
> Removed `??=` syntax

- cypress/integration/pages/dex/[poolpairId].spec.ts
- src/components/commons/OverflowTable.tsx
- src/pages/dex/[poolpairId]/_components/PoolPairDetailsBar.tsx
- src/pages/dex/[poolpairId]/index.page.tsx
- src/pages/dex/_components/PoolPairsCards.tsx
- src/pages/dex/_components/PoolPairsTable.tsx
…page
/kind feature
Fixes #1059
Link: 
<details>
</details>
<details>
</details>
> Implement support for multiple params to access indv. poolpairs

- cypress/integration/pages/dex/[poolpairId].spec.ts
- src/hooks/useAge.tsx
- src/pages/dex/[poolpairId]/_components/PoolPairDetails.tsx
- src/pages/dex/[poolpairId]/_components/PoolPairDetailsBar.tsx
- src/pages/dex/[poolpairId]/_components/SwapCards.tsx
- src/pages/dex/[poolpairId]/_components/SwapTable.tsx
- src/pages/dex/[poolpairId]/index.page.tsx
/kind feature
Fixes #
Link: 
<details>
</details>
<details>
</details>
> `Improvement` indv. poolpair page

- src/components/commons/transactions/TransactionVectorRow.tsx
/kind fix
Fixes # 1085
Link: 
<details>
</details>
<details>
</details>
> Prevent address from overflow in transaction details page

- src/pages/blocks/_components/BlocksCards.tsx
- src/pages/blocks/_components/BlocksTable.tsx
/kind feature
Fixes #1068
Link: 
<details>
</details>
<details>
</details>
> Implemented `useAge` hook across project

- cypress/integration/pages/dex/dex.spec.ts
- src/components/commons/CardList.tsx
- src/pages/dex/_components/PoolPairsCards.tsx
- src/pages/dex/_components/PoolPairsTable.tsx
- src/pages/dex/index.page.tsx
/kind feature
Adding functionality to sort new data point (Primary Token Price) added to the DEX
Additionally fixed the state of the sort choice (between web & mobile) by having it maintained by parents 
Fixes #
Link: 
<details>
</details>
<details>
</details>
> `DEX` Add sorting functionality to Primary Token Price

- src/layouts/contexts/WhaleContext.tsx
/kind chore
Bumped testnet to v0.32
> Bumped testnet to v0.32

- src/layouts/Default.tsx
/kind chore
Removed testnet block out of sync banner
> Removed testnet block out of sync banner

- src/components/commons/token/PoolPairSymbolLocal.tsx
- src/pages/dex/[poolpairId]/_components/PoolPairDetails.tsx
- src/pages/dex/[poolpairId]/_components/SwapCards.tsx
- src/pages/dex/[poolpairId]/_components/SwapTable.tsx
- src/pages/dex/[poolpairId]/index.page.tsx
- src/pages/oracles/_components/OracleGraph.tsx
/kind fix
Fixes #
Link: 
<details>
</details>
<details>
</details>
> `DEX`: Minor UI adjustments

- content/events/index.ts
/kind chore
- Added April dToken distribution countdown
> Added April dToken distribution countdown

- src/layouts/contexts/WhaleContext.tsx
/kind chore
Bumped ocean to v0.32
> Bumped ocean to v0.32

- content/events/index.ts
/kind chore
- Added FCR block countdown
> Added FCR countdown

- src/layouts/contexts/WhaleContext.tsx
/kind chore
Bumped testnet to v0.33
> Bumped testnet to v0.33

- content/prices/index.ts
/kind chore
- Added May tickers
> Added may tickers

- src/pages/oracles/[symbol].page.tsx
/kind fix
Newly added ticker - BRK.B contains symbol '.' which fails alphanumeric validation 
Fixes #
Link: 
<details>
</details>
<details>
</details>
> `ORACLES` Fix oracle ticker url path validation

- src/layouts/contexts/WhaleContext.tsx
/kind chore
Bumped mainnet to v0.33
> Bumped Mainnet to v0.33

- .github/workflows/oss-governance-bot.yml
> chore(workflows): update oss-governance-bot.yml to use new package

- src/layouts/Default.tsx
- src/pages/dex/[poolpairId]/_components/PoolPairDetailsBar.tsx
- src/pages/dex/_components/PoolPairsCards.tsx
- src/pages/dex/_components/PoolPairsTable.tsx
- src/pages/dex/index.page.tsx
- src/pages/vaults/hooks/TokenPrice.ts
- src/store/dex.tsx
- src/store/index.ts
/kind feature
Instead of path finding logic for dex prices, there is now a new whale API to fetch DEX prices. This will improve performance on Scan
Fixes #
Link: 
<details>
</details>
<details>
</details>
> `DEX` prices to pull from Whale API

- content/events/index.ts
Added May dToken Reward Distribution Countdown event
> chore(events): Added May dToken Reward Distribution Countdown event

- src/pages/dex/[poolpairId]/index.page.tsx
Fixes #
Link: 
<details>
</details>
<details>
</details>
> fix(dex): Fix Dex individual page link

- src/pages/dex/[poolpairId]/_components/PoolPairDetailsBar.tsx
- src/pages/dex/[poolpairId]/index.page.tsx
Auto refresh poolpair details and txns
> feat(poolpair): Auto refresh poolpair details and txns

- content/events/index.ts
Added Fort Canning Crunch Countdown event
> chore(events): Added Fort Canning Crunch Countdown

- content/events/index.ts
Added June dTokens Reward Distribution Countdown event
> chore(events): Added June dTokens Reward Distribution Countdown

- src/pages/vaults/utils/NextCollateralizationRatio.tsx
Signed-off-by: Suraj Auwal <siradjiawoual@gmail.com>
As per dfip, dusd price should be 0.99 when used as collateral instead of 1
Fixes #1175
Link: 
<details>
</details>
<details>
</details>
> fix(vaults): Changed next Collateral value to use 0.99 as dusd value

- src/pages/transactions/_components/DfTx/DfTxSetFutureSwap.tsx
- src/pages/transactions/_components/TransactionDfTx.tsx
Add DfTx table for upcoming future swap
Fixes #
Link: 
<details>
</details>
<details>
</details>
> feat(dftx): Add DfTx for Future Swap

- src/layouts/contexts/WhaleContext.tsx
> chore(whale): Bumped mainnet to v0.35

- src/layouts/contexts/WhaleContext.tsx
> chore(whale): Bumped mainnet to 0.36

- src/pages/blocks/countdown/[query]/index.page.tsx
Fixed countdown only counting down every 10 secs instead of 1 sec.
> fix(countdown): Fixed countdown

- .github/CODEOWNERS
Fixes #
Link: 
<details>
</details>
<details>
</details>
> feat(docs): updated codeowners

- src/layouts/Default.tsx
Added announcement message regarding dAMZN ocean regression issue
> chore(announcement): Added announcement message

- src/layouts/Default.tsx
Removed announcement message regarding dAMZN ocean regression issue
Fixes #
Link: 
<details>
</details>
<details>
</details>
> chore(ui-ux): removed dAMZN announcement

- src/pages/blocks/_components/BlocksTable.tsx
- src/pages/dex/_components/PoolPairsTable.tsx
- src/pages/oracles/_components/OracleFeed.tsx
- src/pages/oracles/_components/OracleTickerDetail.tsx
- src/pages/vaults/_components/commons/VaultHealthBar.tsx
Fixes #
Link: 
<details>
</details>
<details>
</details>
> chore(ui-ux): fixed dark mode asset classes tags on Oracles page

- src/components/commons/AdaptiveList.tsx
Signed-off-by: Suraj Auwal <siradjiawoual@gmail.com>
Fixes #
Link: 
<details>
</details>
<details>
</details>
> fix(ui-ux): Added word break to adaptive list to prevent overflow

- src/pages/vaults/_components/commons/VaultHealthBar.tsx
Fixes #
Link: 
<details>
</details>
<details>
</details>
> fix(ui-ux): updated next collateral ratio miss match

- package-lock.json
- package.json
- src/components/commons/searchbar/SearchBar.tsx
- src/components/commons/searchbar/SearchResult.tsx
- src/pages/vaults/[vaultid]/_components/VaultIdDetails.tsx
- src/pages/vaults/[vaultid]/index.page.tsx
- src/pages/vaults/_components/commons/VaultHealthBar.tsx
- src/pages/vaults/utils/NextCollateralizationRatio.tsx
Fixes #
Link: 
<details>
</details>
<details>
</details>
> chore(release): rc/1.1.0

- src/pages/address/_components/AddressSummaryTable.tsx
- src/pages/transactions/_components/DfTx/DfTxCompositeSwap.tsx
Add number format on token amount
Fixes #1271
Link: 
<details>
</details>
<details>
</details>
> feat(ui-ux): add number format on token amount

- src/pages/dex/[poolpairId]/_components/SwapTable.tsx
dd padding left on token symbol
Fixes #1270
Link: 
<details>
</details>
<details>
</details>
> feat(ui-ux): `DEX` - Pool Pair page - swap history - add padding left on token symbol

- cypress/e2e/components/WarningBanner.spec.ts
- next.config.js
- public/_headers
- src/components/commons/banner/WarningBanner.tsx
- src/components/index/IndexHeader.tsx
- src/components/index/SupplyStats.tsx
- src/hooks/useApiStatus.tsx
- src/layouts/Default.tsx
- src/layouts/components/HeaderCountBar.tsx
- src/store/index.ts
- src/store/stats.tsx
- src/store/website.tsx
An automatic message should be displayed when there is no new blocks minted for 45 mins.
Fixes #856
Link: 
<details>
</details>
<details>
</details>
> feat(ui-ux): Automatic display of warning message (No blocks minted > 45 mins) 

- src/pages/dex/[poolpairId]/_components/PoolPairDetailsBar.tsx
- src/pages/dex/[poolpairId]/_components/PoolPairDexStabilizationFee.tsx
- src/pages/dex/[poolpairId]/index.page.tsx
- Add DUSD-DFI dex stabilization on DUSD-DFI page
- One issue is Dex stabilization component is not using the whole width in small screens
Fixes #1296
Link: 
<details>
</details>
<details>
</details>
> feature(core): add dex stabilization fee on dusd-dfi 

- cypress/e2e/components/WarningBanner.spec.ts
- next.config.js
- public/_headers
- src/components/commons/banner/WarningBanner.tsx
- src/components/index/IndexHeader.tsx
- src/components/index/SupplyStats.tsx
- src/hooks/useApiStatus.tsx
- src/layouts/Default.tsx
- src/layouts/components/HeaderCountBar.tsx
- src/pages/dex/[poolpairId]/_components/PoolPairDetailsBar.tsx
- src/pages/dex/[poolpairId]/_components/PoolPairDexStabilizationFee.tsx
- src/pages/dex/[poolpairId]/index.page.tsx
- src/store/index.ts
- src/store/stats.tsx
- src/store/website.tsx
Fixes #
Link: 
<details>
</details>
<details>
</details>
> chore(release): rc/1.3.0

- src/pages/dex/[poolpairId]/_components/PoolPairDexStabilizationFee.tsx
- src/pages/dex/[poolpairId]/index.page.tsx
- Make dex stabilization fee dynamic
Fixes #
Link: 
<details>
</details>
<details>
</details>
> make dex stabilization fee dynamic

- src/pages/dex/[poolpairId]/_components/PoolPairDexStabilizationFee.tsx
- src/pages/dex/[poolpairId]/index.page.tsx
Fix dex stabilization ui mobile responsive
Fixes #1303 
Link: 
<details>
</details>
<details>
</details>
> chore(ui-ux): fix dex ui mobile responsive

- src/pages/dex/_components/PoolPairsCards.tsx
- src/pages/dex/_components/PoolPairsTable.tsx
- src/pages/dex/index.page.tsx
Quick fixes for error on `dex` page.
Fixes #
Link: 
<details>
</details>
<details>
</details>
> fix(dex): Quick fixes for dex page

- src/pages/dex/_components/PoolPairsCards.tsx
- src/pages/dex/_components/PoolPairsTable.tsx
Fixes #
Link: 
<details>
</details>
<details>
</details>
> fix(dex): Fixed USDC & USDT DFI pairs

- src/pages/vaults/hooks/TokenPrice.ts
The useTokenPrice is still using the `/v1`. Filtering it out to get the data from the correct pair
Fixes #
Link: 
<details>
</details>
<details>
</details>
> feat(dex): filter out v1 pair

- src/pages/vaults/_components/VaultMobileCard.tsx
- src/pages/vaults/_components/commons/VaultCollateralizationRatio.tsx
- src/pages/vaults/_components/commons/VaultHealthBar.tsx
- src/pages/vaults/_components/commons/VaultStatus.tsx
- src/pages/vaults/_components/commons/VaultTableRow.tsx
- To display 2dp of col ratio in vault list and detail page
- Also update dp of min col ratio to be consistent
Fixes #
Link: 
<details>
</details>
<details>
</details>
> fix(ui-ux): display 2dp of col ratio

- package-lock.json
- package.json
- src/pages/vaults/_components/VaultMobileCard.tsx
Fixes #
Link: 
<details>
</details>
<details>
</details>
> chore(release): rc/1.4.0

- cypress/e2e/pages/dex/[poolpairId].spec.ts
- src/pages/dex/[poolpairId]/index.page.tsx
- Remove unused code
- Improve test description
Fixes #
Link: 
<details>
</details>
<details>
</details>
> chore(ui-ux): remove unused code

- cypress/e2e/pages/dex/[poolpairId].spec.ts
- src/pages/dex/[poolpairId]/index.page.tsx
Fixes #
Link: 
<details>
</details>
<details>
</details>
> feat(ui-ux): remove DUSD price

- src/components/commons/banner/WarningBanner.tsx
- src/layouts/Default.tsx
Fixes #
Link: 
<details>
</details>
<details>
</details>
> fix(ui-ux): inverted color

- .github/CODEOWNERS
Fixes #
Link: 
<details>
</details>
<details>
</details>
> chore(docs): setup codeowners

- src/layouts/Default.tsx
- src/pages/auctions/_components/commons/BidAmountValue.tsx
- src/pages/dex/[poolpairId]/_components/PoolPairDetailsBar.tsx
- src/pages/dex/_components/PoolPairsCards.tsx
- src/pages/dex/_components/PoolPairsTable.tsx
- src/pages/vaults/[vaultid]/auctions/_components/DesktopAuctionDetails.tsx
- src/pages/vaults/[vaultid]/auctions/_components/MobileAuctionDetails.tsx
- src/pages/vaults/hooks/CalculateAuctionsValue.tsx
- src/pages/vaults/hooks/TokenPrice.ts
- src/store/dexPrices.tsx
- src/store/index.ts
Fixes #1324
Link: 
<details>
</details>
<details>
</details>
> refactor(ui-ux): api integration for dex price

- docker-compose.yml
- package-lock.json
- package.json
Fixes #
Link: 
<details>
</details>
<details>
</details>
> chore(deps): bump jellyfish packages

- src/layouts/Default.tsx
Fixes #
Link: 
<details>
</details>
<details>
</details>
> fix(ui-ux): SEO updates

- src/components/icons/assets/tokens/_TokenDefault.tsx
- src/components/icons/assets/tokens/index.ts
Fixes #
Link: 
<details>
</details>
<details>
</details>
> feature(ui-ux): update loans avatar

- cypress/e2e/pages/transactions/DfTx/CompositeSwap.spec.ts
- cypress/e2e/pages/transactions/DfTx/PoolSwap.spec.ts
- cypress/e2e/pages/transactions/RawTransaction.spec.ts
- src/hooks/useSwapToAmount.tsx
- src/pages/transactions/[txid].page.tsx
- src/pages/transactions/_components/DfTx/DfTxCompositeSwap.tsx
- src/pages/transactions/_components/DfTx/DfTxPoolSwap.tsx
- src/pages/transactions/_components/TransactionDfTx.tsx
Fixes #1277
Link: 
<details>
</details>
<details>
</details>
> feature(ui-ux): added to amount in Composite Swap txn type

- src/pages/dex/_components/PoolPairsCards.tsx
- src/pages/dex/_components/PoolPairsTable.tsx
- src/pages/dex/hooks/CalculatePoolPairPrices.ts
- As titled, fix for mobile, desktop is fixed in #1433 
Fixes #
Link: 
<details>
</details>
<details>
</details>
> fix(dex): dex price on mobile

- package-lock.json
- package.json
Fixes #
Link: 
<details>
</details>
<details>
</details>
> chore(deps): upgrade cypress to ^11.1.0

- docker-compose.yml
Fixes #
Link: 
<details>
</details>
<details>
</details>
> feature(deps): update scan docker file

- src/layouts/components/Header.tsx
Fixes #
Link: 
<details>
</details>
<details>
</details>
> feat(styles): updated active state for more menu and resolve error

- src/layouts/components/Header.tsx
This PR updates the dropdown menu for the navbar and add additional `rootPathName` in dropDownLinks items
Fixes #
Link: 
<details>
</details>
<details>
</details>
> feature(stylings): update dropdown menu for navbar

- src/pages/on-chain-governance/_components/PreviousVotingCycleProposalsCards.tsx
- src/pages/on-chain-governance/_components/PreviousVotingCycleProposalsTable.tsx
- src/pages/on-chain-governance/_components/PreviousVotingCyclesCard.tsx
- src/pages/on-chain-governance/_components/PreviousVotingCyclesTable.tsx
- src/pages/on-chain-governance/enum/onChainGovernanceTitles.ts
- src/pages/on-chain-governance/index.page.tsx
- src/pages/on-chain-governance/previous-voting-cycles/[pvid].page.tsx
- src/pages/on-chain-governance/previous-voting-cycles/index.page.tsx
- src/pages/on-chain-governance/shared/getTotalVotes.ts
This PR adds previous voting cycles and previous voting cycle page 
Fixes #
Link: 
<details>
</details>
<details>
</details>
The proposalid page not reachable yet to update pathname to proposalD instead of proposalName
> feat(ui-ux): add previous voting cycles and previous proposals based on cycle

- cypress/e2e/components/SearchBar.spec.ts
- cypress/e2e/layouts/header.spec.ts
- src/layouts/components/Header.tsx
As titled
Fixes #
This PR fixes failing test cases for header e2e
Link:
<details>
</details>
<details>
</details>
> chore(e2e): update failing tests for header

- src/pages/on-chain-governance/[proposalId]/index.page.tsx
- src/pages/on-chain-governance/_components/ProposalDetail.tsx
As titled
Fixes #
This PR also fixes word-break for proposal title in details page if title is long without spaces
Link:
<details>
</details>
<details>
</details>
> feat(ui-ux): update proposal detail mobile view ui

- src/pages/on-chain-governance/create/index.page.tsx
As titled
Fixes #
Link:
<details>
</details>
<details>
</details>
> fix(ui-ux): fix create proposal command from cycle to cycles

- src/pages/on-chain-governance/index.page.tsx
As titled
Fixes #
Added catch to rpc call 
Link:
<details>
</details>
<details>
</details>
> fix(ui-ux): fixed error handling when call listGovProposals

- src/pages/on-chain-governance/[proposalId]/index.page.tsx
As titled
Fixes #
We should only show the current cycle votes in the votes table 
<details>
<summary>
Before fix
</summary>
</details>
<details>
<summary>
After fix
</summary>
</details>
Link:
<details>
</details>
<details>
</details>
> fix(ui-ux): fixed listing gov proposal votes call to get current cycle

- package.json
- pnpm-lock.yaml
- src/hooks/useAuctionTimeLeft.tsx
- src/layouts/contexts/Environment.ts
- src/layouts/contexts/NetworkContext.tsx
- src/layouts/contexts/WhaleContext.tsx
- src/pages/on-chain-governance/[proposalId]/index.page.tsx
- src/pages/on-chain-governance/_components/ConfirmVoteDialog.tsx
- src/pages/on-chain-governance/_components/ProposalTable.tsx
- src/pages/on-chain-governance/create/index.page.tsx
- src/pages/on-chain-governance/index.page.tsx
- src/pages/on-chain-governance/shared/getSecondsPerBlock.ts
- src/pages/on-chain-governance/shared/localStorageHelper.ts
- src/store/dexPrices.tsx
- src/store/poolpairs.tsx
- src/store/stats.tsx
- src/store/supply.tsx
Fixes #
Link:
<details>
</details>
<details>
</details>
> feature(walletkit): use walletkit for network config

- src/components/commons/CursorPagination.tsx
- src/pages/on-chain-governance/_components/ProposalCard.tsx
- src/pages/on-chain-governance/_components/ProposalTable.tsx
- src/pages/on-chain-governance/index.page.tsx
As titled
Fixes #
Link:
<details>
</details>
<details>
</details>
There is an issue with the pagination where by if we have 30 proposals it should only have 3 pages but a 4th page is appearing in the number buttons for CursorPagination resulting in below image
> feat(ui-ux): add cursorPagination for listing page

- src/pages/on-chain-governance/[proposalId]/index.page.tsx
Fixes #
Link:
<details>
</details>
<details>
</details>
> feature(ui-ux): added pagination for voting list in proposal detail page

- src/pages/on-chain-governance/index.page.tsx
Fixes #
Link:
<details>
</details>
<details>
</details>
> chore(ui-ux): hide OCG announcement

- src/pages/on-chain-governance/_components/ConfirmVoteDialog.tsx
Fixes #
Link:
<details>
</details>
<details>
</details>
> chore(ui-ux): hide neutral vote btn from submit vote flow

- src/pages/on-chain-governance/_components/ProposalCard.tsx
- src/pages/on-chain-governance/_components/ProposalDetail.tsx
- src/pages/on-chain-governance/_components/ProposalTable.tsx
Fixes #
Link:
<details>
</details>
<details>
</details>
> chore(ui-ux): redirect on block countdown page for future blocks link

- src/pages/on-chain-governance/_components/EmergencyChip.tsx
- src/pages/on-chain-governance/_components/ProposalCard.tsx
- src/pages/on-chain-governance/_components/ProposalDetail.tsx
- src/pages/on-chain-governance/_components/ProposalTable.tsx
Fixes #
Link:
<details>
</details>
<details>
</details>
> feature(ui-ux): added emergency chip for DFIP emergency proposal

- src/pages/on-chain-governance/_components/ConfirmVoteDialog.tsx
Fixes #
Link:
<details>
</details>
<details>
</details>
> feature(ui-ux): disabled neutral btn

- src/pages/on-chain-governance/_components/ProposalCard.tsx
- src/pages/on-chain-governance/_components/ProposalDetail.tsx
- src/pages/on-chain-governance/_components/ProposalTable.tsx
- src/pages/on-chain-governance/_components/ReviewProposal.tsx
- src/pages/on-chain-governance/create/index.page.tsx
- src/pages/on-chain-governance/enum/onChainGovernanceTitles.ts
- src/utils/commons/LinkValidator.ts
Fixes #
Link:
<details>
</details>
<details>
</details>
> feature(ui-ux): added reddit support for proposal creation

- public/_redirects
Fixes #
Link:
<details>
</details>
<details>
</details>
> feature(url): redirect ocg to on-chain-governance

- src/pages/on-chain-governance/_components/EmergencyChip.tsx
Fixes #
Link:
<details>
</details>
<details>
</details>
> feature(url): update label

- src/pages/on-chain-governance/_components/ProposalCard.tsx
- src/pages/on-chain-governance/_components/ProposalDetail.tsx
- src/pages/on-chain-governance/_components/ProposalTable.tsx
- src/pages/on-chain-governance/_components/VotesTable.tsx
Fixes #
Link:
<details>
</details>
<details>
</details>
> feature(ocg): copy updates

- src/pages/on-chain-governance/_components/GettingStartedInfo.tsx
- src/pages/on-chain-governance/create/index.page.tsx
- As titled
Fixes #
Link:
<details>
</details>
<details>
</details>
> fix(ocg): include reddit in create proposal

- src/pages/on-chain-governance/index.page.tsx
- As titled
- Default tab to `ALL` proposal type
Fixes #
Link:
<details>
</details>
<details>
</details>
> feature(ocg): add all tab to listing

- src/pages/blocks/countdown/[query]/index.page.tsx
- src/pages/on-chain-governance/[proposalId]/index.page.tsx
- src/pages/on-chain-governance/_components/ProposalCard.tsx
- src/pages/on-chain-governance/_components/ProposalDetail.tsx
- src/pages/on-chain-governance/_components/ProposalTable.tsx
- src/pages/on-chain-governance/enum/onChainGovernanceTitles.ts
- src/pages/on-chain-governance/index.page.tsx
- src/pages/on-chain-governance/shared/dateHelper.ts
- src/pages/on-chain-governance/shared/getCycleEndTime.tsx
- src/pages/on-chain-governance/shared/getSecondsPerBlock.ts
- src/pages/on-chain-governance/shared/getTotalVotes.ts
- src/pages/on-chain-governance/shared/useCycleEndTime.tsx
- As titled
- Use ISO format with no timezone offset `YYYY-MM-DDThh:mm:ssZ` e.g.: `1997-07-16T19:20:30Z`
- Fix precision error when calculating votes percentage
- Fix `getSecondsPerBlock`
- Add dynamic seconds per block to countdown page
Fixes #
Link:
<details>
</details>
<details>
</details>
> fix(ocg): display timestamp at listing and details

- src/pages/consortium/_components/SearchInput.tsx
- src/pages/consortium/asset_breakdown/_components/AssetBreakdownTable.tsx
Fixes #
Link:
<details>
</details>
<details>
</details>
> fix(ui-ux): input size & USDT symbol on burned token fixes

- src/pages/governance/_components/ProposalCard.tsx
- src/pages/governance/_components/ProposalDetail.tsx
- src/pages/governance/_components/ProposalTable.tsx
- src/pages/governance/enum/onChainGovernanceTitles.ts
As titled 
1) add transaction ID to proposal detail page 
2) update listing page table header and card header to Transaction ID from Proposal ID
Fixes #
Link:
<details>
</details>
<details>
</details>
> feat(ui-ux): add transaction id enhancement to proposal detail page

- src/pages/governance/[proposalId]/index.page.tsx
- src/pages/governance/_components/VotingResult.tsx
1) update proposal details page voting flow progress bar to tug of war progress bar 
2) included approval threshold indicator in progress bar
3) updated positioning of labels in voting flow 
Fixes #
Link:
<details>
</details>
<details>
</details>
> feat(ui-ux): add ui changes to voting flow

- src/pages/governance/[proposalId]/index.page.tsx
- src/pages/governance/_components/ProposalCard.tsx
- src/pages/governance/_components/ProposalTable.tsx
- src/pages/governance/enum/onChainGovernanceTitles.ts
- To remove `Previous cycle` tab in governance detail page for 1 cycle only proposal
- To add `Requested Amount` to listing page
Fixes #
Link:
<details>
</details>
<details>
</details>
> chore(release): 1.7.0

- cypress/e2e/pages/transactions/DfTx/TokenMint.spec.ts
- As titled, to not block package upgrade for `@waveshq/standard`
Fixes #
Link:
<details>
</details>
<details>
</details>
> chore(e2e): skip tokenmint e2e

- src/pages/oracles/index.page.tsx
Fixes [WEB-47](https://birthday.atlassian.net/browse/WEB-47)
Link:
<details>
</details>
<details>
</details>
[WEB-47]: https://birthday.atlassian.net/browse/WEB-47?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(ui-ux): Rename Loan to dTokens

- src/pages/oracles/index.page.tsx
Popover missed out
Fixes #1739
Link:
<details>
</details>
<details>
</details>
> chore(ui-ux): rename loan -> dtoken (popover)

- .github/workflows/ci-e2e.yml
- .github/workflows/ci.yml
- .npmrc
- package.json
- pnpm-lock.yaml
Fixes #
Link:
<details>
</details>
<details>
</details>
> chore(ops): update pnpm

- src/pages/governance/[proposalId]/index.page.tsx
- src/pages/governance/_components/ProposalCard.tsx
- src/pages/governance/_components/ProposalTable.tsx
- src/pages/governance/_components/VotingResult.tsx
- src/pages/governance/enum/onChainGovernanceTitles.ts
- src/pages/governance/index.page.tsx
- No votes preview for proposals overview page
Fixes [WEB-268](https://birthday.atlassian.net/browse/WEB-268)
Link:
<details>
</details>
<details>
</details>
[WEB-268]: https://birthday.atlassian.net/browse/WEB-268?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui-ux): show progress bar of votes on proposals overview screen

- src/pages/dex/_components/PoolPairsTable.tsx
- As titled
- TODO: fix from the root cause instead of hardcoding everytime new token is added
Fixes #
Link:
<details>
</details>
<details>
</details>
> fix(tokens): temp ugly fix to display dEUROC-dfi link

- src/pages/dex/[poolpairId]/index.page.tsx
- As titled
Fixes #
Link:
<details>
</details>
<details>
</details>
> fix(dex): add stab fee to deuroc-dusd

- src/pages/dex/_components/PoolPairsCards.tsx
> fix(dex): dirty fix poolpair link on mobile

- src/constants/TokenBackedAddress.ts
- src/layouts/components/Header.tsx
- src/pages/dex/_components/PoolPairsCards.tsx
- src/pages/proof-of-backing/_components/BackingCard.tsx
- src/pages/proof-of-backing/_components/BackingTable.tsx
- src/pages/proof-of-backing/index.page.tsx
- src/pages/tokens/[id].page.tsx
- src/pages/tokens/shared/getAllTokens.ts
- Add proof of backing page
- Fix navigation link for `dEUROC-DFI` from DEX list view on mobile
> chore(release): 1.9.0

- docker-compose.yml
Fixes #
Link:
<details>
</details>
<details>
</details>
> fix(core): fixed docker issue for running whale container

- src/components/icons/assets/TwitterIcon.tsx
- src/layouts/components/Footer.tsx
Fixes DFC-171
Link:
<details>
</details>
<details>
</details>
> chore(ui-ux): updated twitter logo to its latest version

- src/constants/TokenBackedAddress.ts
- src/pages/proof-of-backing/_components/BackingTable.tsx
- src/pages/tokens/[id].page.tsx
Add MATIC, SOL and DOT to proof of backing table:
Also add backing address inside token details page:
Fixes #
Link:
<details>
</details>
<details>
</details>
> feat(ui-ux): add matic, sol and dot tokens to proof of backing

- src/components/icons/assets/tokens/XCHF.tsx
- src/components/icons/assets/tokens/dXCHF.tsx
- src/components/icons/assets/tokens/index.ts
- src/constants/TokenBackedAddress.ts
- src/pages/tokens/[id].page.tsx
Fixes #
Link:
<details>
</details>
<details>
</details>
> feat(ui-ux): add svg icon for xchf token

- src/pages/dex/index.page.tsx
- src/pages/tokens/index.page.tsx
Fixes #
Link:
<details>
</details>
<details>
</details>
> fix(ui-ux): filter out burn symbol in DEX table

- src/pages/address/_components/AddressVinVout.tsx
- src/pages/transactions/[txid].page.tsx
- src/pages/transactions/_components/TransactionSummaryTable.tsx
- src/pages/transactions/_components/TransactionVinVout.tsx
- src/utils/commons/evmtx/checkIfEvmTx.ts
Fixes #
Link:
<details>
</details>
<details>
</details>
> feat(ui-ux): handle tx details display for evmtx

- cypress/fixtures/proof-of-backing/backingAddresses.ts
- src/constants/TokenBackedAddress.ts
- Update Quantum backing address to use Levain wallet address
- Display Quantum backing address for dMATIC
Fixes #
Link:
<details>
</details>
<details>
</details>
> feat(ui-ux): update quatum backing address to levain wallet address

- src/layouts/contexts/WhaleContext.tsx
Fixes #
Link:
<details>
</details>
<details>
</details>
> feat(ui-ux): temporarily use stable changi for testnet ocean

- src/layouts/contexts/WhaleContext.tsx
Fixes #
Link:
<details>
</details>
<details>
</details>
> feat(ui-ux): remove custom url for testnet

- cypress/e2e/pages/tokens/tokens-[symbol].spec.ts
- cypress/fixtures/proof-of-backing/backingAddresses.ts
- src/constants/TokenBackedAddress.ts
Fixes #
Link:
<details>
</details>
<details>
</details>
> feat(ui-ux): update doge token backing address

- cypress/e2e/pages/tokens/tokens-[symbol].spec.ts
- cypress/fixtures/proof-of-backing/backingAddresses.ts
- src/constants/TokenBackedAddress.ts
Fixes DFC-403
Link:
<details>
</details>
<details>
</details>
> chore(ops): update proof of backing addresses for dETH, dUSDC, dUSDT, dEUROC, dMATIC, dBTC and dLTC tokens

- cypress/fixtures/proof-of-backing/backingAddresses.ts
- src/constants/TokenBackedAddress.ts
Fixes #
Link:
<details>
</details>
<details>
</details>
> feat(ui-ux): update sui backing address

- next.config.js
- src/pages/transactions/[txid].page.tsx
- src/pages/transactions/_components/RawAccountHistory.tsx
Add "Raw Account History" to Query raw defid account state at a given TxId and TxNo.
> feat(website): add RawAccountHistory to show history at txn history

- cypress/e2e/pages/tokens/tokens-[symbol].spec.ts
- cypress/fixtures/proof-of-backing/backingAddresses.ts
Fixes #1913
Link:
<details>
</details>
<details>
</details>
> feat(test): add backedAddresses for dMATIC

- cypress/e2e/pages/tokens/tokens-[symbol].spec.ts
- cypress/fixtures/proof-of-backing/backingAddresses.ts
- src/constants/TokenBackedAddress.ts
Fixes DFC-403
Link:
<details>
</details>
<details>
</details>
> fix(ui-ux): update bch proof of token address

- cypress/fixtures/proof-of-backing/backingAddresses.ts
- src/constants/TokenBackedAddress.ts
Fixes #
Link:
<details>
</details>
<details>
</details>
> chore(ui-ux): update sol backing address

- src/pages/governance/_components/ConfirmVoteDialog.tsx
Fixes #
Link:
<details>
</details>
<details>
</details>
> fix(governance): enable neutral voting

- cypress/e2e/pages/blocks/[blockId].spec.ts
- cypress/e2e/pages/transactions/[txid].spec.ts
- src/components/commons/MetascanLinkButton.tsx
- src/pages/blocks/[blockId]/index.page.tsx
- src/pages/transactions/[txid].page.tsx
- src/pages/transactions/_components/TransactionHeadings.tsx
- src/pages/transactions/_components/TransactionSummaryTable.tsx
- src/pages/transactions/enum/VmmapTypes.ts
- src/utils/commons/getNetworkParams.ts
Fixes #
Link:
<details>
</details>
<details>
</details>
> feat(ui-ux): include link to metascan for transaction and block details pages

- cypress/fixtures/proof-of-backing/backingAddresses.ts
- src/constants/TokenBackedAddress.ts
- src/pages/proof-of-backing/_components/BackingTable.tsx
- src/pages/tokens/[id].page.tsx
Fixes #DFC-509
Link:
<details>
</details>
<details>
</details>
> fix(ui-ux): add dxchf backing address to proof of backing
