BirthdayResearch/defiscan.live

.idea/dictionaries/fuxing.xml, netlify.toml, package-lock.json, package.json, public/robots.txt, src/components/icons/DeFiChainLogo.tsx, src/layouts/Default.tsx, src/layouts/components/Footer.tsx, src/layouts/components/Header.tsx, src/layouts/contexts/NetworkContext.tsx, src/layouts/contexts/PlaygroundContext.tsx, src/layouts/contexts/WhaleContext.tsx, src/layouts/contexts/api/Environment.ts, src/layouts/contexts/api/NetworkQuery.ts, src/pages/_app.tsx, src/pages/index.tsx
> Also in this PR, removed `import React from "React"` as it's not required, as suggested by https://github.com/DeFiCh/explorer/pull/40#pullrequestreview-704972162
/kind chore
via
```html
<NetworkProvider>
<Main />
</NetworkProvider>
```
allows
```ts
const { network } = useNetworkContext()
// to access context therefore network
```
`Context.Provider` are nested properly and will automatically refresh when deeply nested context refreshes.
```jsx
<NetworkProvider>
<PlaygroundProvider>
<WhaleProvider>
<Header />
<main/>
<Footer />
</WhaleProvider>
</PlaygroundProvider>
</NetworkProvider>
```
```ts
const { network, setNetwork } = useNetworkContext()
```
```ts
const { api, rpc } = usePlaygroundContext()
```
```ts
const api = useWhaleApiClient()
const rpc = useWhaleRpcClient()
```
=> Added layout contexts for Whale, Playground & Network

src/layouts/contexts/PlaygroundContext.tsx, src/layouts/contexts/api/NetworkQuery.ts
=> fix NetworkQuery.ts not to reset path after finding playground network

.idea/scan.iml, cypress.json, cypress/integration/layouts/header.spec.ts, cypress/integration/routing/network_query.spec.ts, cypress/plugins/index.ts, cypress/support/commands.ts, cypress/tsconfig.json, package-lock.json, package.json, src/layouts/Default.tsx, src/layouts/components/Header.tsx, src/layouts/contexts/PlaygroundContext.tsx, src/layouts/contexts/api/NetworkQuery.ts, src/layouts/contexts/api/NetworkQuery.tsx, src/pages/prices.tsx, tsconfig.json
Also added better cypress testing tools
/kind fix
Fixed #66 due to untested code when pushing #64 my bad, I didn't test it. I have thus added an E2E test for it now.
```diff
-        query: isDefaultNetwork(network) ? { network: network } : {}
+        query: isDefaultNetwork(network) ? {} : { network: network }
```
Also: 
- added a bunch of testing QOL improvement to cypress via `@testing-library/cypress/add-commands`.
- fixed `PlaygroundContext.tsx`
- Refactor `useKeepNetworkQueryString` to be a `<KeepNetworkQueryString/>`
=> Fixed routing to retain `?network=`

.eslintrc, src/components/icons/DeFiChainLogo.tsx, src/layouts/Default.tsx, src/layouts/components/Footer.tsx, src/layouts/components/Header.tsx, src/pages/_app.tsx
/kind chore
- Do not allow `export default` as it makes large scaling refactoring effort difficult.
- Top level functions should not use arrow syntax.
=> Update lint to not allow `variable function` and `export default`

README.md, netlify.toml, src/layouts/contexts/WhaleContext.tsx, src/layouts/contexts/index.ts
/kind refactor
[Netlify Plugin NextJs](https://github.com/netlify/netlify-plugin-nextjs) SSR is enabled by default for netlify deployment. Also added `getWhaleApiClient(GetServerSidePropsContext)` to get WhaleApiClient from `getServerSideProps()`.
```ts
import { getWhaleApiClient } from '@contexts'
async function getServerSideProps(context: GetServerSidePropsContext): Promise<GetServerSidePropsResult<any>> {
const client = getWhaleApiClient(context)
return { 
props: { prices: await client.prices.list() }
}
}
```
Added `[[redirects]]` to redirect all domains to `https://defiscan.live`.
=> new domain: `https://defiscan.live`

.eslintrc, src/components/commons/Link.tsx, src/layouts/Default.tsx, src/layouts/components/Footer.tsx, src/layouts/components/Header.tsx, src/layouts/contexts/WhaleContext.tsx, src/layouts/contexts/api/NetworkQuery.tsx, src/layouts/contexts/index.ts
/kind fix
With the introduction of `getServerSideProps`, `KeepNetworkQueryString` won't suffice to replace URL with network querystring e.g.`?network=Playground`. This proves to be difficult as `getServerSideProps` do not run an environment where `useHook` can be set up.
The alternative will be injecting the required querystring into all `<Link>` implementations. Doing it conditionally and manually at each required `<Link>` reference will a gross and unclean project. Hence, this PR implements `import { Link } from '@components/commons/Link'` where the default next `<Link>` implementation is override to provide `KeepNetworkQueryString` `<Link>` implementation. 
- eslint is updated to prevent `next/link` usage.
- `KeepNetworkQueryString` has been removed entirely
=> added custom keep network `<Link/>` implementation

.github/workflows/ci.yml, README.md, cypress/integration/layouts/header.spec.ts, src/layouts/contexts/PlaygroundContext.tsx, src/layouts/contexts/api/Environment.ts
/kind refactor
with SSR, useConnectedPlayground() to find connected playground is invalid as the network is now configured via querystring instead of the state.
Intermediate network switching proves to be difficult via SSR rendering one network while SPA rendering on another.
Also removed SetupPlayground in ci.yml
=> removed `useConnectedPlayground()`

.eslintrc, .idea/inspectionProfiles/Project_Default.xml, package-lock.json, package.json, src/components/commons/Breadcrumb.tsx, src/components/commons/Head.tsx, src/layouts/Default.tsx, src/pages/404.tsx, src/pages/prices/[symbol].tsx, src/pages/prices/index.tsx
/kind feature
Breadcrumb.tsx will now interpolate SEO metadata: 
- https://schema.org BreadcrumbList
- canonical url
- og url
Head.tsx will now override default next/head implementation to allow consistent title and description open graph tags
- Also updated `.idea` configs to ignore title in `<Head/>`
Fixes part of #39
=> Breadcrumb.tsx will now interpolate SEO metadata

src/layouts/Default.tsx, src/layouts/contexts/StoreProvider.tsx, src/pages/_app.tsx, src/store/index.ts, src/store/stats.tsx
/kind refactor
Redux Store is now cached on the client side, on SSR it will be hydrated over. For SPA page load, it will not reload the store anymore.
=> Redux Store is now cached on client side on SSR it will be hydrated over

.eslintrc, src/components/commons/CursorPagination.tsx, src/pages/dex/index.tsx
/kind feature
Added `CursorPagination.tsx` to mock pagination with LSM indexes.
```ts
/**
* To get `next` from Context
* @example const next = CursorPagination.getNext(GetServerSidePropsContext)
*
* To get pages available from Context and next ApiPagedResponse
* @example const pages = CursorPagination.getPages(GetServerSidePropsContext, ApiPagedResponse)
*
* To render the pagination
* @example <CursorPaginationProps pages={pages} path='/...' />
*
* @param {CursorPaginationProps} props
*/
```
Implementation examples:
```ts
export async function getServerSideProps (context: GetServerSidePropsContext): Promise<GetServerSidePropsResult<DexPageProps>> {
const next = CursorPagination.getNext(context)
const items = await getWhaleApiClient(context).poolpairs.list(2, next)
return {
props: {
items: …
```
=> Added CursorPagination for LSM index querying

src/components/commons/Breadcrumb.tsx, src/components/commons/CursorPagination.tsx, src/components/commons/Link.tsx, src/components/prices/PriceFeed.tsx, src/layouts/components/Footer.tsx, src/layouts/components/Header.tsx
/kind fix
All `<Link>` children should include `<a>` to take advantage to browser native linking.
=> Refactor <Link> children to use <a> to take advantage of native linking

.github/workflows/ci-e2e.yml
/kind chore
ci.yml and ci-e2e.yml to always run on push main and '0 1 * * *' due to code coverage
=> ci.yml and ci-e2e.yml to always run on push main and '0 1 * * *'

.imgbotconfig
/kind chore
`/cypress/**` images are part of cypress visual regression.
=> added `.imgbotconfig` to ignore cypress image snapshot

cypress.json, src/components/icons/assets/_Default.tsx, src/components/icons/assets/index.ts
/kind refactor
- cypress.json 8000ms sanity timeout
- @components/icons/assets update to handle getAssetIcon, getNativeIcon, getTokenIcon
=> minor sanity refactoring for cypress and `icons/assets`

cypress/integration/pages/tokens/tokens.spec.ts, src/components/commons/AdaptiveTable.tsx, src/components/commons/CursorPagination.tsx, src/pages/tokens/index.tsx
/kind refactor
- added a more sane testing approach without having to `> > >`.
- updated all `data-testid` to be the component name e.g. `AdaptiveTable.Head`
- for more obvious testid like page title since we should only have 1 `<h1>` per page, just use that instead.
- added conditional rendering for icons (please take note of isDAT, isLPS)
- added a more sane number rendering approach
- design isn't using text-right, please follow and use text-left (omitted as left is default)
- CATEGORIES -> CATEGORY
- `SYMBOL | NAME` instead of `NAME | SYMBOL`
=> `/tokens` page refactor

.idea/codeStyles/Project.xml, .idea/inspectionProfiles/Project_Default.xml, cypress/integration/pages/tokens/tokens-[symbol].spec.ts, src/components/commons/AdaptiveList.tsx, src/components/dex/PoolPairs.tsx, src/pages/dex/index.tsx, src/pages/tokens/[id].tsx, src/pages/tokens/index.tsx, tailwind.config.js
/kind refactor
/kind fix
- fixed tokens-[symbol].spec.ts indentation
- moved `PoolPairs.tsx` to components/dex because it's not a common component, it's a dex specific component
- refactor entire `<TokenRow>` to be a clickable row with hover-group indicator
- For AdaptiveList, don't use opacity-60 on the parent component as it affects child component colors, text-color is more adaptive and consistency for child adaptability 
- Removed content-copy as there isn't any real utility to copying transactions. Users can double click select to copy.
- Removed minWidth extension for tailwind, the developer should stray away from setting number specific utility as that makes it harder to maintain in the long run
- For AdaptiveList, opt to use a table instead of flex. As `table` provides automatic …
=> refactor tokens details

.github/workflows/ci-e2e.yml
/kind fix
Swapped from `npm run dev` to `npm run start` to fix cypress flaky test performance for PriceFeed due to unpredictable build time. 
Fixes #232
=> cypress: `npm run start` instead of `npm run dev`

README.md
/kind chore
Hiding the badge because we are not using it directly anymore.
=> remove TS Standard badge

.github/dependabot.yml
=> set dependabot update schedule to daily from weekly to further shift left deps update timeline

src/layouts/contexts/Environment.ts
/kind refactor
Changes the default development network to MainNet to match default production env. This would allow devs to include the addition of links/href cypress test cases.
Currently in the dev environment, ?network=MainNet will be appended to `href` attributes of every `<Link>` component as MainNet is not default env. If test cases are written to check for urls including the "?network=MainNet" the test cases will pass local/dev env but fail in the CI/prod env and vice versa.
=> Update default dev env network to MainNet

babel.config.js
/kind chore
Fixed babel.config to **not** strip testids in dev mode.
=> Fixed babel config for dev

docker-compose.yml, package-lock.json, package.json
Add `ActivePrice` to `LoanToken`, `CollateralToken` and `VaultLoanTokenAmount` for convenience. This data can be undefined at the root or deeply within for different conditions (next/current halt), need to handle those conditions.
- This PR contains 1 very minor breaking change, rename of `LoanCollateralToken.priceFeedId` to `LoanCollateralToken.fixedIntervalPriceId`.
- MainNet deployment is not yet ready, this is only applicable in Playground till then.
=> Bump whale to 0.14.1 to support ActivePrice data within LoanToken, CollateralToken, VaultLoanTokenAmount

src/components/dex/PoolPairs.tsx
/kind chore
Hide `BURN-DFI` temporarily from being shown on `/dex`.
=> hide BURN-DFI temporary from /dex

src/pages/vaults/_components/commons/RemainingTokensIcon.tsx
/kind fix
Fixes RemainingTokensIcon text alignment on Safari.
=> Fix RemainingTokensIcon alignment on Safari

next.config.js
/kind fix
Adds `ws://localhost:3000/_next/webpack-hmr` into connect-src when in development env. As local dev servers were not loading on Safari as it enforces connect-src policy.
=> Added ws://localhost:3000/ into connect-src

package-lock.json, package.json
Downgraded eslint to v7.32.0 as `eslint-config-standard-*` has not been updated to support eslint v8 yet. Causing dep tree issues on fresh `npm i` runs.
Upgraded
- @defichain/playground-api-client
- @reduxjs/toolkit
- next-sitemap
- nextjs-progressbar
- schema-dts
=> Dependencies upgrades

src/pages/vaults/_components/commons/VaultCollateralizationRatio.tsx, src/pages/vaults/_components/commons/VaultHealthBar.tsx
/kind feature
- Adds warning symbol beside the vaults to give users a warning that their vault may into liquidation.
- Adds a hidden keyword "Vault may go into liquidation" for monitors (uptimerobot) to pick up.
Warning & Keywords are added when the vault's Next Collateralization Ratio is lesser than 1.1x of it's Min. Collateralization Ratio.
Fixes #904 
Link: 
<details>
</details>
<details>
</details>
=> Added warning message when next ratio is 1.1x less than min ratio

.github/workflows/defichain-dependencies.yml, docker-compose.yml, package.json
/kind chore
With https://github.com/DeFiCh/wallet/pull/2325 merged in, we can consolidate the bumping workflow into one on Scan too.
=> chore(dependencies): migrate playground-api to use DeFiCh/jellyfish/apps release

cypress/integration/pages/transactions/RawTransaction.spec.ts, src/pages/transactions/[txid].page.tsx, src/pages/transactions/_components/RawTransaction.tsx, src/pages/transactions/_components/RawTransactionHeadings.tsx, src/pages/transactions/_components/RawTransactionVinVout.tsx
/kind feature
Currently, when transaction is still pending, no information is shown. With this, user will be able to view some information of the pending transaction (redirected from LW) 
Fixes https://github.com/DeFiCh/scan/issues/590
Build on top of https://github.com/DeFiCh/scan/pull/769
Link: 
<details>
</details>
<details>
<summary>Mobile Screenshot</summary> 
</details>
=> `Transaction` Display pending transaction page with raw txn

cypress/integration/pages/transactions/[txid].spec.ts, src/pages/transactions/_components/TransactionSummaryTable.tsx
/kind feature
Display Skipped Transaction for transaction that are skipped
Fixes #861
Link: 
<details>
</details>
=> Display Skipped Transaction for transaction that are skipped #861

src/pages/blocks/countdown/[query]/_components/CountdownSection.tsx, src/pages/blocks/countdown/[query]/index.page.tsx
Updated countdown logic to be deterministic based on the current block's median time.
Caveats: There may be occurrences where the target block is too close to the current block. The countdown will only show 0's as the targetted time has already past. Etherscan shares the same "issue".
=> chore(countdown): Updated countdown logic

src/pages/dex/index.page.tsx
Hide poolpairs that are not swappable (status = false)
=> chore(dex): Hide pools that are not swappable

src/pages/dex/[poolpairId]/_components/PoolPairDexStabilizationFee.tsx, src/pages/dex/[poolpairId]/index.page.tsx
- Display DEX Stabilization fees on 'DUSD-DFI', 'dUSDC-DUSD', 'dUSDT-DUSD'
- Note as of creating the PR the DEX Stabilization fees on 'dUSDC-DUSD', 'dUSDT-DUSD' is not yet available on mainnet and playground
Fixes #
Link: 
<details>
</details>
<details>
</details>
=> feature(dex): display stab fees on usdc,usdt pair

src/pages/dex/_components/PoolPairsTable.tsx
As per the title, this PR changes the calculation of Primary Token Price (USDT) for `/dex` page to follow `/dex/:slug` calculation. Essentially calculation of the value of A based on the value of B using the ratio of ba. While previously, the calculated value of A was based on the value of A using the ratio of ab.
=> chore(dex): invert /dex price calculation to use same price logic as /dex/:id page

src/pages/transactions/_components/DfTx/DfTxSetFutureSwap.tsx
This PR fixes the Text Color for darkmode for futureswaps transactions page
Fixes #
1. added `dark:text-gray-100` for Swap To and Swap From text
Link: https://deploy-preview-1489--defi-scan.netlify.app/transactions/f4466fba51463ad2489c9a469a853b5c499d5709e52c6c4f76f3ed168e6e0bd5?network=Playground
<details>
Before
After 
</details>
<details>
Before
After
</details>
=> fix(ui-ux): added darkmode text color for futureswap destination

src/pages/on-chain-governance/[proposalId]/index.page.tsx
- As titled, to provide consistent pagination behaviour at `/ocg/{id}` page
- Only reproducible when accessing the next page when number of votes for current active page = 10 (pagination size)
Fixes #
Link:
<details>
</details>
<details>
</details>
=> fix(ocg): display pagination UI even when it is empty

.github/workflows/ci.yml, package.json, pnpm-lock.yaml, src/utils/commons/LinkValidator.test.ts, src/utils/commons/LinkValidator.ts
In prod, Reddit links appear as "Link" instead of "Reddit" when the `www` subdomain is not used. This bug is the opposite for GitHub links where it only works if there is no subdomain. 
Fixes [WEB-312](https://birthday.atlassian.net/browse/WEB-312)
Link:
<details>
</details>
<details>
</details>
[WEB-312]: https://birthday.atlassian.net/browse/WEB-312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(ui-ux): subdomain agnostic regex for discussion links

src/pages/dex/[poolpairId]/_components/PoolPairDetailsBar.tsx
This PR fixes the issue where csETH-dETH page is not showing the value
https://defiscan.live/dex/csETH-dETH
Fixes #
Link:
<details>
</details>
<details>
</details>
=> fix(ui-ux): fix the dex poolpairid page 

src/pages/governance/create/index.page.tsx, src/pages/proof-of-backing/index.page.tsx, src/pages/tokens/[id].page.tsx
- As titled, since burn address has more than the default listToken size, i.e.: 30, so we increase the query size
Fixes #
Link:
<details>
</details>
<details>
</details>
=> fix(token): increase listToken limit to get all burned token

src/pages/dex/_components/NonTradeChip.tsx, src/pages/dex/_components/PoolPairsCards.tsx, src/pages/dex/_components/PoolPairsTable.tsx
This PR adds a NonTradeChip component to indicate non tradable BURN2 pairs in poolpairs table
Fixes #
Link:
<details>
</details>
<details>
</details>
=> chore(ui-ux): add non trade chip for poolpairs table and cards for burn2

src/pages/dex/_components/PoolPairsCards.tsx, src/pages/dex/_components/PoolPairsTable.tsx
Fixes #
Link:
<details>
</details>
<details>
</details>
=> fix(ui-ux): redirect of dxchf
